export default [
  { d: 1, q: 'Quel est le plus grand animal vivant actuellement sur Terre ?', c: ['Éléphant d\'Afrique', 'Baleine bleue', 'Requin-baleine', 'Girafe'], a: 1 },
  { d: 1, q: 'Combien de pattes possède une araignée ?', c: ['Six', 'Huit', 'Dix', 'Douze'], a: 1 },
  { d: 1, q: 'Quel est l\'animal terrestre le plus rapide en course ?', c: ['Guépard', 'Lion', 'Lévrier', 'Antilope'], a: 0 },
  { d: 1, q: 'Quel mammifère est capable d\'un vol battu ?', c: ['Écureuil volant', 'Colugo', 'Lémurien', 'Chauve-souris'], a: 3 },
  { d: 1, q: 'Quel est le plus grand oiseau du monde ?', c: ['Autruche', 'Émeu', 'Condor', 'Casoar'], a: 0 },
  { d: 1, q: 'Combien de cœurs possède une pieuvre ?', c: ['Un', 'Deux', 'Trois', 'Quatre'], a: 2 },
  { d: 1, q: 'Quel animal figure sur le logo du WWF ?', c: ['Tigre', 'Panda géant', 'Éléphant', 'Gorille'], a: 1 },
  { d: 1, q: 'Comment appelle-t-on le petit de la vache ?', c: ['Agneau', 'Poulain', 'Chevreau', 'Veau'], a: 3 },
  { d: 1, q: 'Quel est le plus grand félin sauvage ?', c: ['Lion', 'Jaguar', 'Léopard', 'Tigre'], a: 3 },
  { d: 1, q: 'Sur quel continent le kangourou vit-il à l\'état sauvage ?', c: ['Afrique', 'Amérique du Sud', 'Océanie', 'Asie'], a: 2 },
  { d: 1, q: 'Quel est le plus grand reptile vivant ?', c: ['Dragon de Komodo', 'Crocodile marin', 'Anaconda', 'Tortue luth'], a: 1 },
  { d: 1, q: 'Quel insecte l\'apiculteur élève-t-il pour produire du miel ?', c: ['Guêpe', 'Frelon', 'Bourdon', 'Abeille'], a: 3 },
  { d: 1, q: 'Quel animal est surnommé le « roi des animaux » ?', c: ['Lion', 'Tigre', 'Éléphant', 'Ours'], a: 0 },
  { d: 1, q: 'Combien de bosses possède un dromadaire ?', c: ['Aucune', 'Une', 'Deux', 'Trois'], a: 1 },
  { d: 2, q: 'Quel est le plus grand animal terrestre actuel ?', c: ['Rhinocéros blanc', 'Hippopotame', 'Girafe', 'Éléphant d\'Afrique'], a: 3 },
  { d: 2, q: 'Quel oiseau incapable de voler est un excellent nageur ?', c: ['Kiwi', 'Émeu', 'Manchot', 'Autruche'], a: 2 },
  { d: 2, q: 'Combien de compartiments possède l\'estomac de la vache ?', c: ['Un', 'Deux', 'Trois', 'Quatre'], a: 3 },
  { d: 2, q: 'Quel est le plus grand primate vivant ?', c: ['Gorille', 'Orang-outan', 'Chimpanzé', 'Babouin'], a: 0 },
  { d: 2, q: 'Quel mammifère pond des œufs ?', c: ['Pangolin', 'Tatou', 'Ornithorynque', 'Paresseux'], a: 2 },
  { d: 2, q: 'Quel mammifère terrestre a la gestation la plus longue ?', c: ['Girafe', 'Éléphant', 'Rhinocéros', 'Cheval'], a: 1 },
  { d: 2, q: 'À quelle classe d\'animaux appartient la grenouille ?', c: ['Reptiles', 'Poissons', 'Mammifères', 'Amphibiens'], a: 3 },
  { d: 2, q: 'Quel oiseau est capable de voler à reculons ?', c: ['Colibri', 'Martinet', 'Hirondelle', 'Faucon'], a: 0 },
  { d: 2, q: 'Quel est le plus grand poisson du monde ?', c: ['Requin blanc', 'Requin-baleine', 'Espadon', 'Raie manta'], a: 1 },
  { d: 2, q: 'Quel mammifère est réputé le plus lent du monde ?', c: ['Koala', 'Panda', 'Paresseux', 'Tortue'], a: 2 },
  { d: 2, q: 'Quel est le plus grand rongeur du monde ?', c: ['Castor', 'Porc-épic', 'Ragondin', 'Capybara'], a: 3 },
  { d: 2, q: 'Quelle est la plus grande espèce de manchot ?', c: ['Manchot royal', 'Manchot empereur', 'Manchot Adélie', 'Manchot papou'], a: 1 },
  { d: 2, q: 'Combien de vertèbres cervicales possède une girafe ?', c: ['Sept', 'Douze', 'Quatorze', 'Vingt'], a: 0 },
  { d: 2, q: 'Quel oiseau possède la plus grande envergure ?', c: ['Condor des Andes', 'Pélican blanc', 'Aigle royal', 'Albatros hurleur'], a: 3 },
  { d: 3, q: 'Quel animal possède le plus grand œil du règne animal ?', c: ['Baleine bleue', 'Autruche', 'Calmar colossal', 'Éléphant'], a: 2 },
  { d: 3, q: 'À quelle famille appartient le panda roux ?', c: ['Ursidés', 'Ailuridés', 'Procyonidés', 'Mustélidés'], a: 1 },
  { d: 3, q: 'Quel oiseau effectue la plus longue migration annuelle connue ?', c: ['Sterne arctique', 'Cigogne blanche', 'Oie des neiges', 'Barge rousse'], a: 0 },
  { d: 3, q: 'Combien de chromosomes possède le chien domestique ?', c: ['38', '46', '64', '78'], a: 3 },
  { d: 3, q: 'Dans quel pays vit le dragon de Komodo à l\'état sauvage ?', c: ['Philippines', 'Malaisie', 'Indonésie', 'Australie'], a: 2 },
  { d: 3, q: 'Quelle vitesse le faucon pèlerin peut-il dépasser en piqué ?', c: ['100 km/h', '200 km/h', '300 km/h', '500 km/h'], a: 2 },
  { d: 3, q: 'Quel animal marin possède un sang bleu grâce à l\'hémocyanine ?', c: ['Lamproie', 'Limule', 'Anguille', 'Espadon'], a: 1 },
  { d: 3, q: 'Chez quel animal le mâle porte-t-il les œufs dans une poche ventrale ?', c: ['Poisson-clown', 'Crapaud', 'Hippocampe', 'Triton'], a: 2 },
  { d: 3, q: 'Quel animal fut le premier mammifère cloné à partir d\'une cellule adulte, en 1996 ?', c: ['Une brebis', 'Une souris', 'Une vache', 'Une chèvre'], a: 0 },
  { d: 3, q: 'Quelle est la seule espèce de manchot vivant naturellement au nord de l\'équateur ?', c: ['Manchot du Cap', 'Manchot de Humboldt', 'Manchot de Magellan', 'Manchot des Galápagos'], a: 3 },
  { d: 3, q: 'Qu\'est-ce que la « corne » du narval ?', c: ['Une corne osseuse', 'Un cartilage', 'Une dent', 'Une nageoire'], a: 2 },
  { d: 3, q: 'Quel poisson, que l\'on croyait disparu depuis des millions d\'années, a été redécouvert vivant en 1938 ?', c: ['Cœlacanthe', 'Dipneuste', 'Esturgeon', 'Nautile'], a: 0 },
];
