export default [
  { d: 1, q: 'Qui a peint « La Joconde » ?', c: ['Raphaël', 'Léonard de Vinci', 'Michel-Ange', 'Botticelli'], a: 1 },
  { d: 1, q: 'Dans quel musée est exposée « La Joconde » ?', c: ['Le Louvre', 'Les Offices', 'Le Prado', 'Le British Museum'], a: 0 },
  { d: 1, q: 'Qui a peint « La Nuit étoilée » ?', c: ['Claude Monet', 'Paul Gauguin', 'Vincent van Gogh', 'Paul Cézanne'], a: 2 },
  { d: 1, q: 'Qui a sculpté « Le Penseur » ?', c: ['Camille Claudel', 'Antoine Bourdelle', 'Aristide Maillol', 'Auguste Rodin'], a: 3 },
  { d: 1, q: 'Qui a peint « Guernica » ?', c: ['Joan Miró', 'Pablo Picasso', 'Salvador Dalí', 'Francisco de Goya'], a: 1 },
  { d: 1, q: 'Qui a peint « La Jeune Fille à la perle » ?', c: ['Johannes Vermeer', 'Rembrandt', 'Frans Hals', 'Jan Steen'], a: 0 },
  { d: 1, q: 'Qui a peint le plafond de la chapelle Sixtine ?', c: ['Raphaël', 'Le Titien', 'Michel-Ange', 'Le Caravage'], a: 2 },
  { d: 1, q: 'Qui a peint « Impression, soleil levant » ?', c: ['Édouard Manet', 'Auguste Renoir', 'Camille Pissarro', 'Claude Monet'], a: 3 },
  { d: 1, q: 'Dans quelle ville se trouve le musée du Prado ?', c: ['Barcelone', 'Madrid', 'Séville', 'Lisbonne'], a: 1 },
  { d: 1, q: 'Qui a peint « Le Cri » ?', c: ['Edvard Munch', 'Egon Schiele', 'Gustav Klimt', 'James Ensor'], a: 0 },
  { d: 1, q: 'Quel ingénieur a donné son nom à la tour construite à Paris pour l\'Exposition universelle de 1889 ?', c: ['Auguste Perret', 'Louis Vicat', 'Gustave Eiffel', 'Ferdinand de Lesseps'], a: 2 },
  { d: 1, q: 'Qui a peint « La Persistance de la mémoire », célèbre pour ses montres molles ?', c: ['René Magritte', 'Max Ernst', 'Giorgio De Chirico', 'Salvador Dalí'], a: 3 },
  { d: 1, q: 'Dans quelle ville se trouve la Sagrada Família ?', c: ['Madrid', 'Barcelone', 'Valence', 'Bilbao'], a: 1 },
  { d: 1, q: 'Quel musée parisien est installé dans une ancienne gare ?', c: ['Le musée d\'Orsay', 'Le Centre Pompidou', 'Le musée Picasso', 'Le Petit Palais'], a: 0 },
  { d: 2, q: 'Quel architecte a conçu la Sagrada Família ?', c: ['Le Corbusier', 'Santiago Calatrava', 'Antoni Gaudí', 'Ricardo Bofill'], a: 2 },
  { d: 2, q: 'Qui a peint « La Naissance de Vénus » ?', c: ['Le Titien', 'Raphaël', 'Giotto', 'Sandro Botticelli'], a: 3 },
  { d: 2, q: 'Qui a peint « La Grande Vague de Kanagawa » ?', c: ['Hiroshige', 'Hokusai', 'Utamaro', 'Sesshū'], a: 1 },
  { d: 2, q: 'Qui a peint « La Liberté guidant le peuple » ?', c: ['Eugène Delacroix', 'Théodore Géricault', 'Jacques-Louis David', 'Antoine-Jean Gros'], a: 0 },
  { d: 2, q: 'En quelle année Delacroix a-t-il peint « La Liberté guidant le peuple » ?', c: ['1815', '1848', '1830', '1871'], a: 2 },
  { d: 2, q: 'Qui a peint « Le Radeau de la Méduse » ?', c: ['Eugène Delacroix', 'Jacques-Louis David', 'Gustave Courbet', 'Théodore Géricault'], a: 3 },
  { d: 2, q: 'En quelle année Picasso a-t-il peint « Guernica » ?', c: ['1929', '1937', '1942', '1951'], a: 1 },
  { d: 2, q: 'Dans quelle ville se trouve le musée de l\'Ermitage ?', c: ['Saint-Pétersbourg', 'Moscou', 'Vienne', 'Prague'], a: 0 },
  { d: 2, q: 'Qui a peint « La Ronde de nuit » ?', c: ['Johannes Vermeer', 'Pieter Bruegel', 'Rembrandt', 'Rubens'], a: 2 },
  { d: 2, q: 'Qui a peint « Le Déjeuner sur l\'herbe », scandale du Salon des refusés de 1863 ?', c: ['Claude Monet', 'Gustave Courbet', 'Edgar Degas', 'Édouard Manet'], a: 3 },
  { d: 2, q: 'Quel artiste a réalisé la sculpture « La Petite Danseuse de quatorze ans » ?', c: ['Auguste Rodin', 'Edgar Degas', 'Camille Claudel', 'Aristide Maillol'], a: 1 },
  { d: 2, q: 'Quel architecte a conçu la pyramide du Louvre ?', c: ['Ieoh Ming Pei', 'Jean Nouvel', 'Frank Gehry', 'Renzo Piano'], a: 0 },
  { d: 2, q: 'Qui a peint « Le Baiser » (1908), tableau doré conservé à Vienne ?', c: ['Egon Schiele', 'Edvard Munch', 'Gustav Klimt', 'Oskar Kokoschka'], a: 2 },
  { d: 2, q: 'Qui est l\'auteur de « Fontaine », urinoir présenté comme œuvre d\'art en 1917 ?', c: ['Man Ray', 'Francis Picabia', 'Salvador Dalí', 'Marcel Duchamp'], a: 3 },
  { d: 3, q: 'En quelle année le Centre Pompidou a-t-il été inauguré ?', c: ['1969', '1977', '1983', '1989'], a: 1 },
  { d: 3, q: 'Qui a peint « Les Époux Arnolfini » ?', c: ['Jan van Eyck', 'Rogier van der Weyden', 'Hans Memling', 'Jérôme Bosch'], a: 0 },
  { d: 3, q: 'Quel mouvement Kazimir Malevitch a-t-il fondé ?', c: ['Le constructivisme', 'Le futurisme', 'Le suprématisme', 'Le rayonnisme'], a: 2 },
  { d: 3, q: 'Quel architecte a réalisé la coupole de la cathédrale de Florence ?', c: ['Bramante', 'Alberti', 'Palladio', 'Brunelleschi'], a: 3 },
  { d: 3, q: 'Qui a peint le triptyque « Le Jardin des délices » ?', c: ['Pieter Bruegel l\'Ancien', 'Jérôme Bosch', 'Albrecht Dürer', 'Lucas Cranach'], a: 1 },
  { d: 3, q: 'Quel sculpteur a réalisé « Apollon et Daphné », conservé à la galerie Borghèse ?', c: ['Le Bernin', 'Donatello', 'Canova', 'Cellini'], a: 0 },
  { d: 3, q: 'Quel architecte a conçu la villa Savoye à Poissy ?', c: ['Walter Gropius', 'Mies van der Rohe', 'Le Corbusier', 'Frank Lloyd Wright'], a: 2 },
  { d: 3, q: 'Qui a peint « Les Ménines » ?', c: ['Francisco de Goya', 'El Greco', 'Murillo', 'Diego Vélasquez'], a: 3 },
  { d: 3, q: 'Qui a peint « La Danse » (1910), conservée à l\'Ermitage ?', c: ['André Derain', 'Henri Matisse', 'Georges Braque', 'Raoul Dufy'], a: 1 },
  { d: 3, q: 'Quel artiste est l\'auteur des « Campbell\'s Soup Cans » ?', c: ['Andy Warhol', 'Roy Lichtenstein', 'Jasper Johns', 'Keith Haring'], a: 0 },
  { d: 3, q: 'Qui a peint « Un dimanche après-midi à l\'île de la Grande Jatte » ?', c: ['Paul Signac', 'Camille Pissarro', 'Georges Seurat', 'Henri-Edmond Cross'], a: 2 },
  { d: 3, q: 'Qui a peint « Le Tricheur à l\'as de carreau » ?', c: ['Nicolas Poussin', 'Le Caravage', 'Philippe de Champaigne', 'Georges de La Tour'], a: 3 },
];
