export default [
  { d: 1, q: 'Quel est le vrai nom de Johnny Hallyday ?', c: ['Jean-Philippe Smet', 'Claude Moine', 'Michel Colucci', 'Fernand Contandin'], a: 0 },
  { d: 1, q: 'Pour quel film Jean Dujardin a-t-il reçu l\'Oscar du meilleur acteur en 2012 ?', c: ['OSS 117', 'The Artist', 'Les Petits Mouchoirs', 'Brice de Nice'], a: 1 },
  { d: 1, q: 'Quelle actrice française a reçu l\'Oscar de la meilleure actrice en 2008 pour « La Môme » ?', c: ['Audrey Tautou', 'Juliette Binoche', 'Marion Cotillard', 'Sophie Marceau'], a: 2 },
  { d: 1, q: 'Quel chanteur belge a interprété « Formidable » en 2013 ?', c: ['Jacques Brel', 'Angèle', 'Arno', 'Stromae'], a: 3 },
  { d: 1, q: 'Combien de Ballons d\'Or Zinédine Zidane a-t-il remportés ?', c: ['1', '2', '3', '4'], a: 0 },
  { d: 1, q: 'Quel sport pratiquait Joakim Noah, fils de Yannick Noah ?', c: ['Tennis', 'Basket-ball', 'Football', 'Rugby'], a: 1 },
  { d: 1, q: 'Quel acteur incarne le clown Chocolat dans le film « Chocolat » (2016) ?', c: ['Jamel Debbouze', 'Dany Boon', 'Omar Sy', 'Gad Elmaleh'], a: 2 },
  { d: 1, q: 'Quel est le nom de naissance de Mylène Farmer ?', c: ['Mylène Martin', 'Mylène Dupont', 'Mylène Lefèvre', 'Mylène Gautier'], a: 3 },
  { d: 1, q: 'Dans quelle ville est né Zinédine Zidane ?', c: ['Marseille', 'Lyon', 'Paris', 'Alger'], a: 0 },
  { d: 1, q: 'Quel acteur joue Astérix dans « Astérix et Obélix : Mission Cléopâtre » (2002) ?', c: ['Gérard Depardieu', 'Christian Clavier', 'Clovis Cornillac', 'Édouard Baer'], a: 1 },
  { d: 1, q: 'Quel est le vrai nom de Dalida ?', c: ['Annie Chancel', 'Iolanda Rossi', 'Iolanda Gigliotti', 'Maria Conti'], a: 2 },
  { d: 1, q: 'Quel animateur présente « Fort Boyard » à partir de 2003 ?', c: ['Patrice Laffont', 'Jean-Pierre Foucault', 'Nagui', 'Olivier Minne'], a: 3 },
  { d: 1, q: 'Quel footballeur français a remporté le Ballon d\'Or en 2022 ?', c: ['Karim Benzema', 'Kylian Mbappé', 'Antoine Griezmann', 'N\'Golo Kanté'], a: 0 },
  { d: 1, q: 'Quel comédien joue le gendarme Cruchot dans « Le Gendarme de Saint-Tropez » (1964) ?', c: ['Bourvil', 'Louis de Funès', 'Fernandel', 'Jean Gabin'], a: 1 },
  { d: 2, q: 'Dans quelle ville est née Édith Piaf ?', c: ['Marseille', 'Lille', 'Paris', 'Bordeaux'], a: 2 },
  { d: 2, q: 'Quel est le vrai nom de Coluche ?', c: ['Michel Colin', 'Michel Cohen', 'Michel Collet', 'Michel Colucci'], a: 3 },
  { d: 2, q: 'Quelle chanteuse a remporté le concours Eurovision pour la France en 1977 ?', c: ['Marie Myriam', 'Sheila', 'France Gall', 'Sylvie Vartan'], a: 0 },
  { d: 2, q: 'Quel acteur incarne Cyrano de Bergerac dans le film de Jean-Paul Rappeneau (1990) ?', c: ['Jean Rochefort', 'Gérard Depardieu', 'Daniel Auteuil', 'Philippe Noiret'], a: 1 },
  { d: 2, q: 'Avec qui Serge Gainsbourg a-t-il eu sa fille Charlotte ?', c: ['Brigitte Bardot', 'Juliette Gréco', 'Jane Birkin', 'Françoise Hardy'], a: 2 },
  { d: 2, q: 'Sous quel nom de scène Fabien Marsaud est-il connu ?', c: ['Orelsan', 'Soprano', 'Bigflo', 'Grand Corps Malade'], a: 3 },
  { d: 2, q: 'Dans quel film de 1966 Louis de Funès et Bourvil forment-ils un duo ?', c: ['La Grande Vadrouille', 'Le Corniaud', 'Les Aventures de Rabbi Jacob', 'La Folie des grandeurs'], a: 0 },
  { d: 2, q: 'Quel est le nom de famille du chanteur Renaud ?', c: ['Sévran', 'Séchan', 'Serrault', 'Sérieux'], a: 1 },
  { d: 2, q: 'Quelle joueuse de tennis française a remporté Roland-Garros en 2000 ?', c: ['Amélie Mauresmo', 'Marion Bartoli', 'Mary Pierce', 'Nathalie Tauziat'], a: 2 },
  { d: 2, q: 'Quel chanteur a épousé Laeticia Boudou en 1996 ?', c: ['Eddy Mitchell', 'Michel Sardou', 'Claude François', 'Johnny Hallyday'], a: 3 },
  { d: 2, q: 'Quel nageur français a remporté quatre médailles d\'or aux Jeux olympiques de Paris 2024 ?', c: ['Léon Marchand', 'Florent Manaudou', 'Yannick Agnel', 'Alain Bernard'], a: 0 },
  { d: 2, q: 'Dans quelle ville est né Antoine Griezmann ?', c: ['Lyon', 'Mâcon', 'Dijon', 'Grenoble'], a: 1 },
  { d: 2, q: 'Quel acteur incarne OSS 117 dans « Le Caire, nid d\'espions » (2006) ?', c: ['Gilles Lellouche', 'Guillaume Canet', 'Jean Dujardin', 'Benoît Poelvoorde'], a: 2 },
  { d: 2, q: 'Quel animateur a présenté « Le Grand Journal » de Canal+ à sa création en 2004 ?', c: ['Antoine de Caunes', 'Yann Barthès', 'Laurent Ruquier', 'Michel Denisot'], a: 3 },
  { d: 3, q: 'Quel est le vrai nom de Bourvil ?', c: ['André Raimbourg', 'André Bourvil', 'André Roussel', 'André Rimbaud'], a: 0 },
  { d: 3, q: 'Dans quelle ville est né Jean Reno ?', c: ['Marseille', 'Casablanca', 'Madrid', 'Nice'], a: 1 },
  { d: 3, q: 'Quel est le vrai nom de Fernandel ?', c: ['Fernand Cabrol', 'Fernand Raynaud', 'Fernand Contandin', 'Fernand Marin'], a: 2 },
  { d: 3, q: 'Sous quel nom Lucien Ginsburg est-il devenu célèbre ?', c: ['Michel Berger', 'Claude Nougaro', 'Léo Ferré', 'Serge Gainsbourg'], a: 3 },
  { d: 3, q: 'Quel est le nom de naissance de la chanteuse Sheila ?', c: ['Annie Chancel', 'Annie Cordy', 'Annie Girardot', 'Annie Chapelle'], a: 0 },
  { d: 3, q: 'En quelle année Yannick Noah a-t-il remporté Roland-Garros ?', c: ['1981', '1983', '1985', '1987'], a: 1 },
  { d: 3, q: 'Quel est le vrai nom de Julien Clerc ?', c: ['Paul-Alain Clerc', 'Julien Leclerc', 'Paul-Alain Leclerc', 'Jean-Paul Clerc'], a: 2 },
  { d: 3, q: 'Dans quelle ville est né Omar Sy ?', c: ['Paris', 'Dakar', 'Bondy', 'Trappes'], a: 3 },
  { d: 3, q: 'Quel nom de scène a pris Claude Moine ?', c: ['Eddy Mitchell', 'Dick Rivers', 'Hugues Aufray', 'Richard Anthony'], a: 0 },
  { d: 3, q: 'Quelle actrice a été l\'épouse d\'Yves Montand ?', c: ['Jeanne Moreau', 'Simone Signoret', 'Michèle Morgan', 'Danielle Darrieux'], a: 1 },
  { d: 3, q: 'Quel cycliste français a remporté cinq fois le Tour de France, en 1985 pour la dernière fois ?', c: ['Laurent Fignon', 'Richard Virenque', 'Bernard Hinault', 'Bernard Thévenet'], a: 2 },
  { d: 3, q: 'Quel acteur incarne le père de Vic dans « La Boum » (1980) ?', c: ['Jean-Pierre Marielle', 'Michel Piccoli', 'Jean Rochefort', 'Claude Brasseur'], a: 3 },
];
