export default [
  { d: 1, q: 'Qui a réalisé « Titanic », sorti en 1997 ?', c: ['James Cameron', 'Steven Spielberg', 'Ridley Scott', 'Peter Jackson'], a: 0 },
  { d: 1, q: 'Quel acteur incarne Jack Sparrow dans la saga « Pirates des Caraïbes » ?', c: ['Orlando Bloom', 'Johnny Depp', 'Geoffrey Rush', 'Brad Pitt'], a: 1 },
  { d: 1, q: 'Quel film français de 2011 réunit Omar Sy et François Cluzet ?', c: ['La Haine', 'Le Dîner de cons', 'Intouchables', 'Les Choristes'], a: 2 },
  { d: 1, q: 'Qui a réalisé « Le Fabuleux Destin d\'Amélie Poulain » (2001) ?', c: ['Luc Besson', 'Cédric Klapisch', 'Michel Gondry', 'Jean-Pierre Jeunet'], a: 3 },
  { d: 1, q: 'Quel acteur joue le rôle-titre de « Forrest Gump » (1994) ?', c: ['Tom Hanks', 'Robin Williams', 'Kevin Costner', 'Tom Cruise'], a: 0 },
  { d: 1, q: 'Qui a réalisé « Pulp Fiction » (1994) ?', c: ['Martin Scorsese', 'Quentin Tarantino', 'Oliver Stone', 'David Fincher'], a: 1 },
  { d: 1, q: 'Dans quelle ville est décernée la Palme d\'or ?', c: ['Venise', 'Berlin', 'Cannes', 'Deauville'], a: 2 },
  { d: 1, q: 'Quel film de 1966 réunit Louis de Funès et Bourvil ?', c: ['Les Bronzés', 'Le Gendarme de Saint-Tropez', 'La Folie des grandeurs', 'La Grande Vadrouille'], a: 3 },
  { d: 1, q: 'Qui a réalisé « Jurassic Park » (1993) ?', c: ['Steven Spielberg', 'George Lucas', 'Robert Zemeckis', 'Ron Howard'], a: 0 },
  { d: 1, q: 'Quelle actrice tient le rôle principal de « La Boum » (1980) ?', c: ['Isabelle Adjani', 'Sophie Marceau', 'Emmanuelle Béart', 'Juliette Binoche'], a: 1 },
  { d: 1, q: 'Quel acteur incarne Harry Potter au cinéma ?', c: ['Rupert Grint', 'Tom Felton', 'Daniel Radcliffe', 'Matthew Lewis'], a: 2 },
  { d: 1, q: 'Quel studio d\'animation a produit « Toy Story » (1995) ?', c: ['DreamWorks', 'Studio Ghibli', 'Illumination', 'Pixar'], a: 3 },
  { d: 1, q: 'Qui a réalisé « Le Cinquième Élément » (1997) ?', c: ['Luc Besson', 'Jean-Jacques Annaud', 'Mathieu Kassovitz', 'Jean-Pierre Jeunet'], a: 0 },
  { d: 1, q: 'Quel acteur incarne Rocky Balboa ?', c: ['Arnold Schwarzenegger', 'Sylvester Stallone', 'Bruce Willis', 'Chuck Norris'], a: 1 },
  { d: 2, q: 'Quel film a remporté la Palme d\'or en 1994 ?', c: ['Forrest Gump', 'Trois couleurs : Rouge', 'Pulp Fiction', 'Le Roi lion'], a: 2 },
  { d: 2, q: 'Quel film français a remporté la Palme d\'or en 2008 ?', c: ['Un prophète', 'La Vie d\'Adèle', 'Amour', 'Entre les murs'], a: 3 },
  { d: 2, q: 'Qui a réalisé « Sueurs froides » (« Vertigo », 1958) ?', c: ['Alfred Hitchcock', 'Orson Welles', 'Billy Wilder', 'Stanley Kubrick'], a: 0 },
  { d: 2, q: 'Quel film a remporté l\'Oscar du meilleur film lors de la cérémonie de 2020 ?', c: ['1917', 'Parasite', 'Joker', 'Le Mans 66'], a: 1 },
  { d: 2, q: 'Qui a réalisé « Les Quatre Cents Coups » (1959) ?', c: ['Jean-Luc Godard', 'Claude Chabrol', 'François Truffaut', 'Éric Rohmer'], a: 2 },
  { d: 2, q: 'Quel acteur a remporté l\'Oscar du meilleur acteur en 2016 pour « The Revenant » ?', c: ['Matt Damon', 'Eddie Redmayne', 'Michael Fassbender', 'Leonardo DiCaprio'], a: 3 },
  { d: 2, q: 'Qui a réalisé « Inception » (2010) ?', c: ['Christopher Nolan', 'Denis Villeneuve', 'Darren Aronofsky', 'David Fincher'], a: 0 },
  { d: 2, q: 'Quel film de Hayao Miyazaki a remporté l\'Oscar du meilleur film d\'animation en 2003 ?', c: ['Princesse Mononoké', 'Le Voyage de Chihiro', 'Mon voisin Totoro', 'Le Château ambulant'], a: 1 },
  { d: 2, q: 'Quel film de 1995 réalisé par Mathieu Kassovitz met en scène Vincent Cassel ?', c: ['Les Rivières pourpres', 'Dobermann', 'La Haine', 'Irréversible'], a: 2 },
  { d: 2, q: 'Quel acteur incarne le Joker dans « The Dark Knight » (2008) ?', c: ['Jack Nicholson', 'Joaquin Phoenix', 'Jared Leto', 'Heath Ledger'], a: 3 },
  { d: 2, q: 'Quel film a remporté la Palme d\'or en 2013 ?', c: ['La Vie d\'Adèle', 'Amour', 'Dheepan', 'Titane'], a: 0 },
  { d: 2, q: 'Qui a réalisé « Le Parrain » (1972) ?', c: ['Martin Scorsese', 'Francis Ford Coppola', 'Brian De Palma', 'Sergio Leone'], a: 1 },
  { d: 2, q: 'Quel acteur français a remporté l\'Oscar du meilleur acteur en 2012 pour « The Artist » ?', c: ['Vincent Cassel', 'Guillaume Canet', 'Jean Dujardin', 'Gilles Lellouche'], a: 2 },
  { d: 2, q: 'En quelle année est sorti le premier film « Star Wars » ?', c: ['1974', '1975', '1976', '1977'], a: 3 },
  { d: 3, q: 'Qui a réalisé « Le Samouraï » (1967) avec Alain Delon ?', c: ['Jean-Pierre Melville', 'Henri Verneuil', 'Claude Sautet', 'Jacques Deray'], a: 0 },
  { d: 3, q: 'Quel film de Maurice Pialat a remporté la Palme d\'or en 1987 ?', c: ['Le Grand Bleu', 'Sous le soleil de Satan', 'Camille Claudel', 'Au revoir les enfants'], a: 1 },
  { d: 3, q: 'Qui a réalisé « Le Voyage dans la Lune » (1902) ?', c: ['Louis Lumière', 'Léon Gaumont', 'Georges Méliès', 'Charles Pathé'], a: 2 },
  { d: 3, q: 'Quel compositeur a signé la musique de « Le Bon, la Brute et le Truand » (1966) ?', c: ['Nino Rota', 'John Williams', 'Hans Zimmer', 'Ennio Morricone'], a: 3 },
  { d: 3, q: 'Quelle actrice a remporté le César de la meilleure actrice en 2013 pour « Amour » ?', c: ['Emmanuelle Riva', 'Isabelle Huppert', 'Marion Cotillard', 'Catherine Deneuve'], a: 0 },
  { d: 3, q: 'Quel film a remporté l\'Oscar du meilleur film lors de la cérémonie de 1998 ?', c: ['L.A. Confidential', 'Titanic', 'Will Hunting', 'Bienvenue à Gattaca'], a: 1 },
  { d: 3, q: 'Qui a réalisé « Les Parapluies de Cherbourg » (1964) ?', c: ['Alain Resnais', 'Louis Malle', 'Jacques Demy', 'Agnès Varda'], a: 2 },
  { d: 3, q: 'Quelle réalisatrice a remporté la Palme d\'or en 2021 pour « Titane » ?', c: ['Céline Sciamma', 'Justine Triet', 'Claire Denis', 'Julia Ducournau'], a: 3 },
  { d: 3, q: 'Qui a réalisé « Les Enfants du paradis » (1945) ?', c: ['Marcel Carné', 'Jean Renoir', 'Julien Duvivier', 'René Clair'], a: 0 },
  { d: 3, q: 'Quel film de Stanley Kubrick est sorti en 1968 ?', c: ['Orange mécanique', '2001, l\'Odyssée de l\'espace', 'Shining', 'Barry Lyndon'], a: 1 },
  { d: 3, q: 'Quel film d\'Akira Kurosawa est sorti en 1954 ?', c: ['Rashōmon', 'Ran', 'Les Sept Samouraïs', 'Kagemusha'], a: 2 },
  { d: 3, q: 'Quel film a remporté la Palme d\'or en 2023 ?', c: ['Titane', 'Sans filtre', 'La Zone d\'intérêt', 'Anatomie d\'une chute'], a: 3 },
];
