export default [
  { d: 1, q: 'De quelle ville la bouillabaisse est-elle la spécialité ?', c: ['Nice', 'Marseille', 'Toulon', 'Sète'], a: 1 },
  { d: 1, q: 'De quelle région la choucroute est-elle la spécialité ?', c: ['Bretagne', 'Lorraine', 'Alsace', 'Nord'], a: 2 },
  { d: 1, q: 'De quelle région la quiche du même nom est-elle originaire ?', c: ['Lorraine', 'Alsace', 'Bourgogne', 'Savoie'], a: 0 },
  { d: 1, q: 'De quel pays la paella est-elle originaire ?', c: ['Italie', 'Portugal', 'Mexique', 'Espagne'], a: 3 },
  { d: 1, q: 'De quel pays la moussaka est-elle un plat traditionnel ?', c: ['Turquie', 'Grèce', 'Liban', 'Maroc'], a: 1 },
  { d: 1, q: 'Avec quel lait le roquefort est-il fabriqué ?', c: ['Lait de vache', 'Lait de chèvre', 'Lait de brebis', 'Lait de bufflonne'], a: 2 },
  { d: 1, q: 'De quelle région le camembert est-il originaire ?', c: ['Normandie', 'Bretagne', 'Picardie', 'Auvergne'], a: 0 },
  { d: 1, q: 'De quelle région le kouign-amann est-il originaire ?', c: ['Normandie', 'Bretagne', 'Vendée', 'Alsace'], a: 1 },
  { d: 1, q: 'Quel est l\'ingrédient principal du guacamole ?', c: ['La tomate', 'Le poivron', 'L\'avocat', 'La courgette'], a: 2 },
  { d: 1, q: 'De quel pays le tiramisu est-il originaire ?', c: ['France', 'Espagne', 'Grèce', 'Italie'], a: 3 },
  { d: 1, q: 'Quelle ville a donné son nom à une célèbre moutarde ?', c: ['Dijon', 'Meaux', 'Reims', 'Orléans'], a: 0 },
  { d: 1, q: 'Quelle ville est réputée pour son nougat ?', c: ['Montpellier', 'Montélimar', 'Montauban', 'Montargis'], a: 1 },
  { d: 1, q: 'Quel fruit garnit traditionnellement le clafoutis ?', c: ['La pomme', 'La poire', 'La cerise', 'L\'abricot'], a: 2 },
  { d: 1, q: 'De quelle province canadienne la poutine est-elle originaire ?', c: ['Ontario', 'Alberta', 'Manitoba', 'Québec'], a: 3 },
  { d: 2, q: 'Quel cépage est utilisé pour produire le beaujolais rouge ?', c: ['Gamay', 'Pinot noir', 'Syrah', 'Merlot'], a: 0 },
  { d: 2, q: 'De quel cépage sont issus les grands vins rouges de Bourgogne ?', c: ['Cabernet sauvignon', 'Pinot noir', 'Grenache', 'Malbec'], a: 1 },
  { d: 2, q: 'Quelle herbe aromatique parfume la sauce béarnaise ?', c: ['Le basilic', 'La ciboulette', 'L\'estragon', 'Le thym'], a: 2 },
  { d: 2, q: 'Quels sont les deux ingrédients d\'un roux ?', c: ['Œuf et huile', 'Lait et farine', 'Beurre et sucre', 'Beurre et farine'], a: 3 },
  { d: 3, q: 'Dans quel village près de Lyon Paul Bocuse tenait-il son restaurant ?', c: ['Collonges-au-Mont-d\'Or', 'Vienne', 'Mionnay', 'Villefranche-sur-Saône'], a: 0 },
  { d: 3, q: 'Quel chef a codifié la cuisine française dans « Le Guide culinaire » en 1903 ?', c: ['Antonin Carême', 'Auguste Escoffier', 'Paul Bocuse', 'Alain Ducasse'], a: 1 },
  { d: 2, q: 'Quelle chaîne diffuse l\'émission « Top Chef » en France ?', c: ['TF1', 'France 2', 'M6', 'Canal+'], a: 2 },
  { d: 2, q: 'Quel fromage entre dans la tartiflette ?', c: ['Le comté', 'Le munster', 'Le cantal', 'Le reblochon'], a: 3 },
  { d: 2, q: 'De quel massif le comté est-il originaire ?', c: ['Le Jura', 'Les Vosges', 'Le Massif central', 'Les Pyrénées'], a: 0 },
  { d: 2, q: 'Comment appelle-t-on la découpe de légumes en fins bâtonnets ?', c: ['Brunoise', 'Julienne', 'Mirepoix', 'Chiffonade'], a: 1 },
  { d: 2, q: 'De quel pays le gouda est-il originaire ?', c: ['Danemark', 'Belgique', 'Pays-Bas', 'Suisse'], a: 2 },
  { d: 2, q: 'Quelle pâtisserie est la spécialité de Bordeaux ?', c: ['Le calisson', 'La madeleine', 'Le macaron', 'Le canelé'], a: 3 },
  { d: 2, q: 'De quel pays le ceviche est-il un plat emblématique ?', c: ['Pérou', 'Brésil', 'Cuba', 'Colombie'], a: 0 },
  { d: 2, q: 'Quel légume est à la base de l\'aligot avec la tome fraîche ?', c: ['Le chou', 'La pomme de terre', 'Le navet', 'La carotte'], a: 1 },
  { d: 2, q: 'De quelle ville italienne la pizza margherita est-elle originaire ?', c: ['Rome', 'Milan', 'Naples', 'Palerme'], a: 2 },
  { d: 2, q: 'Quelle ville est réputée pour ses calissons ?', c: ['Avignon', 'Nîmes', 'Arles', 'Aix-en-Provence'], a: 3 },
  { d: 3, q: 'Quel chef a lancé la cuisson sous vide en restauration en 1974 ?', c: ['Georges Pralus', 'Michel Guérard', 'Pierre Troisgros', 'Roger Vergé'], a: 0 },
  { d: 3, q: 'Pour quelle cantatrice Escoffier a-t-il créé la pêche Melba ?', c: ['Maria Callas', 'Nellie Melba', 'Adelina Patti', 'Jenny Lind'], a: 1 },
  { d: 3, q: 'Quel scientifique japonais a identifié le goût umami en 1908 ?', c: ['Jōkichi Takamine', 'Hideki Yukawa', 'Kikunae Ikeda', 'Shibasaburō Kitasato'], a: 2 },
  { d: 3, q: 'En quelle année le premier Guide Michelin a-t-il été publié ?', c: ['1890', '1895', '1905', '1900'], a: 3 },
  { d: 3, q: 'Dans quelle ville se déroule le concours du Bocuse d\'Or ?', c: ['Lyon', 'Paris', 'Dijon', 'Strasbourg'], a: 0 },
  { d: 3, q: 'Quel ancien roi de Pologne, devenu duc de Lorraine, est associé à l\'origine du baba au rhum en Lorraine ?', c: ['Casimir III', 'Stanislas Leszczynski', 'Jean III Sobieski', 'Auguste II'], a: 1 },
  { d: 3, q: 'Quel ingrédient caractérise la sauce hollandaise avec le beurre ?', c: ['La crème', 'La farine', 'Le jaune d\'œuf', 'Le vin blanc'], a: 2 },
  { d: 3, q: 'Quel pays est le berceau du bobotie, gratin de viande hachée aux épices ?', c: ['Inde', 'Indonésie', 'Kenya', 'Afrique du Sud'], a: 3 },
  { d: 3, q: 'De quelle ville la pissaladière est-elle la spécialité ?', c: ['Nice', 'Marseille', 'Perpignan', 'Bastia'], a: 0 },
  { d: 3, q: 'Quel chef a été nommé « Cuisinier du siècle » par le guide Gault et Millau en 1990 ?', c: ['Paul Bocuse', 'Joël Robuchon', 'Alain Chapel', 'Bernard Loiseau'], a: 1 },
];
