export default [
  { d: 1, q: 'À quelle ère géologique appartiennent les dinosaures ?', c: ['Paléozoïque', 'Mésozoïque', 'Cénozoïque', 'Précambrien'], a: 1 },
  { d: 1, q: 'Quel grand carnivore est célèbre pour ses tout petits bras ?', c: ['Vélociraptor', 'Stégosaure', 'Tyrannosaure', 'Tricératops'], a: 2 },
  { d: 1, q: 'Combien de cornes possède le Tricératops ?', c: ['Une', 'Deux', 'Trois', 'Quatre'], a: 2 },
  { d: 1, q: 'De quoi se nourrissait le Diplodocus ?', c: ['De viande', 'De poissons', 'D\'insectes', 'De plantes'], a: 3 },
  { d: 1, q: 'Quel dinosaure porte des plaques osseuses sur le dos et des pointes au bout de la queue ?', c: ['Stégosaure', 'Ankylosaure', 'Spinosaure', 'Iguanodon'], a: 0 },
  { d: 1, q: 'Quelle période s\'achève par la disparition des dinosaures non aviens ?', c: ['Trias', 'Jurassique', 'Permien', 'Crétacé'], a: 3 },
  { d: 1, q: 'Il y a combien de millions d\'années les dinosaures non aviens ont-ils disparu ?', c: ['6', '66', '200', '650'], a: 1 },
  { d: 1, q: 'Quel film de Steven Spielberg sorti en 1993 met en scène des dinosaures recréés ?', c: ['Godzilla', 'Jurassic Park', 'Dinosaure', 'King Kong'], a: 1 },
  { d: 1, q: 'Quels animaux actuels descendent directement des dinosaures ?', c: ['Lézards', 'Crocodiles', 'Tortues', 'Oiseaux'], a: 3 },
  { d: 1, q: 'Comment appelle-t-on les scientifiques qui étudient les fossiles ?', c: ['Archéologues', 'Géologues', 'Paléontologues', 'Biologistes'], a: 2 },
  { d: 1, q: 'Que signifie le mot « dinosaure », formé à partir du grec ?', c: ['Terrible lézard', 'Grand reptile', 'Roi des reptiles', 'Vieux monstre'], a: 0 },
  { d: 1, q: 'Quelle est l\'hypothèse dominante pour expliquer l\'extinction des dinosaures ?', c: ['Une épidémie', 'Un impact d\'astéroïde', 'Une inondation', 'Une famine'], a: 1 },
  { d: 1, q: 'Quelle est la première période du Mésozoïque ?', c: ['Trias', 'Jurassique', 'Crétacé', 'Dévonien'], a: 0 },
  { d: 1, q: 'Comment les dinosaures se reproduisaient-ils ?', c: ['En mettant bas', 'Par bourgeonnement', 'En pondant des œufs', 'Par division'], a: 2 },
  { d: 2, q: 'À quel groupe appartient le Ptéranodon ?', c: ['Dinosaures', 'Oiseaux', 'Ptérosaures', 'Chauves-souris'], a: 2 },
  { d: 2, q: 'Comment appelle-t-on le groupe des dinosaures à long cou comme le Diplodocus ?', c: ['Théropodes', 'Sauropodes', 'Cératopsiens', 'Ornithopodes'], a: 1 },
  { d: 2, q: 'Dans quel pays se trouve le cratère de Chicxulub ?', c: ['Mexique', 'Inde', 'Australie', 'Canada'], a: 0 },
  { d: 2, q: 'À quel groupe de dinosaures appartient le Tyrannosaure ?', c: ['Sauropodes', 'Ankylosaures', 'Cératopsiens', 'Théropodes'], a: 3 },
  { d: 2, q: 'De quoi le corps du Vélociraptor était-il recouvert, d\'après les fossiles ?', c: ['De plumes', 'D\'une carapace', 'De plaques osseuses', 'De poils'], a: 0 },
  { d: 2, q: 'Quel animal fossile du Jurassique est considéré comme l\'un des plus anciens oiseaux connus ?', c: ['Ptéranodon', 'Hesperornis', 'Archaeopteryx', 'Quetzalcoatlus'], a: 2 },
  { d: 2, q: 'Quel dinosaure possède une massue osseuse au bout de la queue ?', c: ['Stégosaure', 'Tricératops', 'Parasaurolophus', 'Ankylosaure'], a: 3 },
  { d: 2, q: 'Quel dinosaure à bec de canard porte une longue crête creuse sur la tête ?', c: ['Parasaurolophus', 'Iguanodon', 'Pachycéphalosaure', 'Ankylosaure'], a: 0 },
  { d: 2, q: 'Combien de doigts le Tyrannosaure avait-il à chaque main ?', c: ['Un', 'Deux', 'Trois', 'Quatre'], a: 1 },
  { d: 2, q: 'Quelle était la longueur approximative d\'un Tyrannosaure adulte ?', c: ['4 mètres', '12 mètres', '25 mètres', '40 mètres'], a: 1 },
  { d: 2, q: 'Pendant combien de millions d\'années environ les dinosaures non aviens ont-ils vécu ?', c: ['16', '65', '165', '500'], a: 2 },
  { d: 2, q: 'Que signifie le nom « Tricératops » ?', c: ['Roi cornu', 'Tête cuirassée', 'Lézard à trois pointes', 'Visage à trois cornes'], a: 3 },
  { d: 2, q: 'Quel supercontinent unique existait au début de l\'ère des dinosaures ?', c: ['Gondwana', 'Pangée', 'Laurasie', 'Rodinia'], a: 1 },
  { d: 2, q: 'Le Compsognathus avait à peu près la taille de quel animal actuel ?', c: ['Un poulet', 'Un cheval', 'Un lion', 'Un éléphant'], a: 0 },
  { d: 3, q: 'Quel est le plus long dinosaure carnivore connu ?', c: ['Tyrannosaure', 'Giganotosaure', 'Spinosaure', 'Allosaure'], a: 2 },
  { d: 3, q: 'Dans quel pays les fossiles d\'Archaeopteryx ont-ils été découverts ?', c: ['Chine', 'Allemagne', 'Royaume-Uni', 'États-Unis'], a: 1 },
  { d: 3, q: 'Quel fut le premier dinosaure à recevoir un nom scientifique, en 1824 ?', c: ['Iguanodon', 'Hylaeosaurus', 'Diplodocus', 'Megalosaurus'], a: 3 },
  { d: 3, q: 'Qui a inventé le mot « dinosaure » en 1842 ?', c: ['Richard Owen', 'Charles Darwin', 'Georges Cuvier', 'Gideon Mantell'], a: 0 },
  { d: 3, q: 'Dans quel État américain a été découvert « Sue », le célèbre squelette de Tyrannosaure ?', c: ['Montana', 'Utah', 'Dakota du Sud', 'Wyoming'], a: 2 },
  { d: 3, q: 'Quel sauropode géant découvert en Argentine compte parmi les plus lourds dinosaures connus ?', c: ['Brachiosaure', 'Argentinosaurus', 'Diplodocus', 'Apatosaure'], a: 1 },
  { d: 3, q: 'Quel élément chimique, anormalement abondant dans la couche géologique de la fin du Crétacé, a soutenu l\'hypothèse de l\'astéroïde ?', c: ['Uranium', 'Platine', 'Fer', 'Iridium'], a: 3 },
  { d: 3, q: 'Quel duo père-fils a proposé en 1980 l\'hypothèse de l\'impact d\'astéroïde ?', c: ['Les Alvarez', 'Les Leakey', 'Les Bakker', 'Les Sereno'], a: 0 },
  { d: 3, q: 'Quel dinosaure découvert en Chine en 1996 fut le premier dinosaure non avien à plumes connu ?', c: ['Microraptor', 'Yutyrannus', 'Sinosauropteryx', 'Oviraptor'], a: 2 },
  { d: 3, q: 'Quelle province canadienne abrite le Dinosaur Provincial Park ?', c: ['Québec', 'Ontario', 'Colombie-Britannique', 'Alberta'], a: 3 },
  { d: 3, q: 'Quel est le plus grand ptérosaure connu ?', c: ['Ptéranodon', 'Quetzalcoatlus', 'Rhamphorhynchus', 'Dimorphodon'], a: 1 },
  { d: 3, q: 'Près de quelle ville française a-t-on découvert de nombreux œufs de dinosaures fossilisés ?', c: ['Aix-en-Provence', 'Bordeaux', 'Grenoble', 'Nantes'], a: 0 },
];
