export default [
  { d: 1, q: 'Quelle fleur jaune se transforme en boule de graines que l\'on souffle ?', c: ['Bouton d\'or', 'Souci', 'Tournesol', 'Pissenlit'], a: 3 },
  { d: 1, q: 'Quelle fleur offre-t-on traditionnellement le 1er mai en France ?', c: ['Muguet', 'Rose', 'Œillet', 'Lilas'], a: 0 },
  { d: 1, q: 'Quelle fleur est traditionnellement associée à la Saint-Valentin ?', c: ['Tulipe', 'Orchidée', 'Pivoine', 'Rose'], a: 3 },
  { d: 1, q: 'Quelle fleur est associée à la Toussaint en France ?', c: ['Lys', 'Chrysanthème', 'Dahlia', 'Iris'], a: 1 },
  { d: 1, q: 'Quelle fleur jaune à bulbe annonce le printemps ?', c: ['Bleuet', 'Coquelicot', 'Jonquille', 'Lavande'], a: 2 },
  { d: 1, q: 'Quelle fleur violette est cultivée en Provence pour son parfum ?', c: ['Violette', 'Lavande', 'Iris', 'Lilas'], a: 1 },
  { d: 1, q: 'Quelle fleur rouge des champs symbolise le souvenir des soldats au Royaume-Uni ?', c: ['Tulipe', 'Rose', 'Pivoine', 'Coquelicot'], a: 3 },
  { d: 1, q: 'Quelle fleur effeuille-t-on en disant « il m\'aime, un peu, beaucoup… » ?', c: ['Pâquerette', 'Marguerite', 'Tournesol', 'Pissenlit'], a: 1 },
  { d: 1, q: 'Quelle fleur est le symbole de la royauté française ?', c: ['Rose', 'Iris', 'Lys', 'Œillet'], a: 2 },
  { d: 1, q: 'Quelle fleur sauvage bleue pousse dans les champs de céréales ?', c: ['Bleuet', 'Myosotis', 'Jacinthe', 'Violette'], a: 0 },
  { d: 1, q: 'Comment s\'appelle la science qui étudie les plantes ?', c: ['Zoologie', 'Géologie', 'Écologie', 'Botanique'], a: 3 },
  { d: 1, q: 'De quelle fleur le safran est-il extrait ?', c: ['Tulipe', 'Crocus', 'Souci', 'Lys'], a: 1 },
  { d: 1, q: 'Comment appelle-t-on le transport du pollen jusqu\'au pistil ?', c: ['Germination', 'Fécondation', 'Pollinisation', 'Floraison'], a: 2 },
  { d: 1, q: 'Quel peintre a réalisé la série des « Nymphéas » ?', c: ['Monet', 'Renoir', 'Manet', 'Cézanne'], a: 0 },
  { d: 2, q: 'Dans quel pays se trouve le parc floral de Keukenhof ?', c: ['Belgique', 'Danemark', 'Pays-Bas', 'Allemagne'], a: 2 },
  { d: 2, q: 'Quel arbre en fleurs est célébré au Japon lors du hanami ?', c: ['Prunier', 'Cerisier', 'Pommier', 'Magnolia'], a: 1 },
  { d: 2, q: 'Quelle plante est la fleur nationale de l\'Écosse ?', c: ['Chardon', 'Trèfle', 'Rose', 'Jonquille'], a: 0 },
  { d: 2, q: 'Quel est l\'organe mâle de la fleur ?', c: ['Pistil', 'Sépale', 'Étamine', 'Pétale'], a: 2 },
  { d: 2, q: 'Quel est l\'organe femelle de la fleur ?', c: ['Pistil', 'Étamine', 'Corolle', 'Calice'], a: 0 },
  { d: 2, q: 'Comment appelle-t-on l\'ensemble des pétales d\'une fleur ?', c: ['Calice', 'Bractée', 'Ovaire', 'Corolle'], a: 3 },
  { d: 2, q: 'Quelle fleur a provoqué une bulle spéculative aux Pays-Bas au XVIIe siècle ?', c: ['Rose', 'Jacinthe', 'Tulipe', 'Orchidée'], a: 2 },
  { d: 2, q: 'Quelle plante produit la plus grande fleur individuelle du monde ?', c: ['Rafflesia', 'Lotus', 'Nénuphar géant', 'Magnolia'], a: 0 },
  { d: 2, q: 'Quelle fleur est un symbole de pureté dans le bouddhisme ?', c: ['Jasmin', 'Hibiscus', 'Nénuphar', 'Lotus'], a: 3 },
  { d: 2, q: 'Quelle fleur Van Gogh a-t-il peinte dans sa célèbre série de natures mortes réalisée à Arles ?', c: ['Iris', 'Tournesols', 'Roses', 'Lys'], a: 1 },
  { d: 2, q: 'Dans quel village se trouve le jardin de Claude Monet ?', c: ['Barbizon', 'Auvers-sur-Oise', 'Giverny', 'Moret-sur-Loing'], a: 2 },
  { d: 2, q: 'De quelle plante à fleurs la vanille est-elle issue ?', c: ['Orchidée', 'Jasmin', 'Magnolia', 'Frangipanier'], a: 0 },
  { d: 2, q: 'Qui a dessiné les jardins du château de Versailles ?', c: ['Mansart', 'Le Brun', 'Le Vau', 'Le Nôtre'], a: 3 },
  { d: 2, q: 'Dans quel pays a eu lieu la révolution des Œillets en 1974 ?', c: ['Espagne', 'Portugal', 'Grèce', 'Italie'], a: 1 },
  { d: 3, q: 'De quel empire la tulipe a-t-elle été introduite en Europe au XVIe siècle ?', c: ['Empire perse', 'Empire moghol', 'Empire ottoman', 'Empire chinois'], a: 2 },
  { d: 3, q: 'Quelle plante possède la plus grande inflorescence non ramifiée et dégage une odeur de chair en décomposition ?', c: ['Arum titan', 'Rafflesia', 'Victoria amazonica', 'Agave'], a: 0 },
  { d: 3, q: 'Quelle fleur est l\'emblème de la ville de Toulouse ?', c: ['Rose', 'Violette', 'Iris', 'Mimosa'], a: 1 },
  { d: 3, q: 'Quelle fleur orange orne les autels du Jour des morts au Mexique ?', c: ['Œillet d\'Inde', 'Chrysanthème', 'Lys', 'Dahlia'], a: 0 },
  { d: 3, q: 'Quelle fleur est l\'emblème officiel de l\'État d\'Hawaï ?', c: ['Orchidée', 'Frangipanier', 'Bougainvillier', 'Hibiscus'], a: 3 },
  { d: 3, q: 'À quelle famille botanique appartiennent la marguerite, le pissenlit et le tournesol ?', c: ['Rosacées', 'Astéracées', 'Liliacées', 'Lamiacées'], a: 1 },
  { d: 3, q: 'À quelle famille botanique appartient la lavande ?', c: ['Astéracées', 'Rosacées', 'Lamiacées', 'Iridacées'], a: 2 },
  { d: 3, q: 'Quelle est la fleur nationale du Mexique ?', c: ['Dahlia', 'Cactus', 'Poinsettia', 'Orchidée'], a: 0 },
  { d: 3, q: 'Combien de pétales possède typiquement une fleur de pommier ?', c: ['Trois', 'Quatre', 'Cinq', 'Six'], a: 2 },
  { d: 3, q: 'Quels pigments donnent leurs teintes bleues et violettes à de nombreuses fleurs ?', c: ['Carotènes', 'Anthocyanes', 'Chlorophylles', 'Mélanines'], a: 1 },
  { d: 3, q: 'Quelle plante est surnommée « rose de Noël » ?', c: ['Camélia', 'Perce-neige', 'Cyclamen', 'Hellébore'], a: 3 },
  { d: 3, q: 'Quelle fleur a donné son nom à la révolution tunisienne de 2011 ?', c: ['Rose', 'Œillet', 'Jasmin', 'Tulipe'], a: 2 },
];
