export default [
  { d: 1, q: 'Quelle est la capitale de l\'Australie ?', c: ['Sydney', 'Canberra', 'Melbourne', 'Perth'], a: 1 },
  { d: 1, q: 'Quel est le plus long fleuve de France ?', c: ['La Loire', 'La Seine', 'Le Rhône', 'La Garonne'], a: 0 },
  { d: 1, q: 'Quel est le plus haut sommet des Alpes ?', c: ['Le Cervin', 'Le Mont Rose', 'Le Mont Blanc', 'La Jungfrau'], a: 2 },
  { d: 1, q: 'Quelle est la capitale du Canada ?', c: ['Toronto', 'Montréal', 'Vancouver', 'Ottawa'], a: 3 },
  { d: 1, q: 'Quel est le plus grand océan du monde ?', c: ['Atlantique', 'Pacifique', 'Indien', 'Arctique'], a: 1 },
  { d: 1, q: 'Quel est le plus grand désert chaud du monde ?', c: ['Sahara', 'Gobi', 'Kalahari', 'Atacama'], a: 0 },
  { d: 1, q: 'Quelle est la capitale de l\'Espagne ?', c: ['Barcelone', 'Séville', 'Madrid', 'Valence'], a: 2 },
  { d: 1, q: 'Quel est le plus grand pays du monde par sa superficie ?', c: ['Canada', 'Chine', 'États-Unis', 'Russie'], a: 3 },
  { d: 1, q: 'Quel fleuve traverse Paris ?', c: ['La Loire', 'La Seine', 'La Marne', 'Le Rhône'], a: 1 },
  { d: 1, q: 'Sur quel continent se trouve l\'Égypte ?', c: ['Afrique', 'Asie', 'Europe', 'Océanie'], a: 0 },
  { d: 1, q: 'Quelle est la capitale du Japon ?', c: ['Osaka', 'Kyoto', 'Tokyo', 'Nagoya'], a: 2 },
  { d: 1, q: 'Quel est le plus long fleuve d\'Afrique ?', c: ['Le Congo', 'Le Niger', 'Le Zambèze', 'Le Nil'], a: 3 },
  { d: 1, q: 'Quelle est la capitale de l\'Italie ?', c: ['Milan', 'Rome', 'Naples', 'Turin'], a: 1 },
  { d: 1, q: 'Quelle chaîne de montagnes abrite l\'Everest ?', c: ['L\'Himalaya', 'Les Andes', 'Le Caucase', 'Les Rocheuses'], a: 0 },
  { d: 2, q: 'Quelle est la capitale de la Turquie ?', c: ['Istanbul', 'Izmir', 'Ankara', 'Antalya'], a: 2 },
  { d: 2, q: 'Quel détroit sépare l\'Espagne du Maroc ?', c: ['Le Bosphore', 'Gibraltar', 'Ormuz', 'Messine'], a: 1 },
  { d: 2, q: 'Quel est le plus grand lac d\'Afrique ?', c: ['Le lac Tchad', 'Le lac Tanganyika', 'Le lac Malawi', 'Le lac Victoria'], a: 3 },
  { d: 2, q: 'Combien de pays partagent une frontière terrestre avec la France métropolitaine ?', c: ['8', '6', '7', '9'], a: 0 },
  { d: 2, q: 'Quelle est la préfecture de la Corse-du-Sud ?', c: ['Bastia', 'Corte', 'Ajaccio', 'Porto-Vecchio'], a: 2 },
  { d: 2, q: 'Quelle est la capitale du Brésil ?', c: ['Rio de Janeiro', 'Brasília', 'São Paulo', 'Salvador'], a: 1 },
  { d: 2, q: 'Quel volcan domine la baie de Naples ?', c: ['L\'Etna', 'Le Stromboli', 'Le Vulcano', 'Le Vésuve'], a: 3 },
  { d: 2, q: 'Quel est le plus haut sommet d\'Afrique ?', c: ['Le Kilimandjaro', 'Le mont Kenya', 'Le Ruwenzori', 'Le mont Cameroun'], a: 0 },
  { d: 2, q: 'Quelle ville est la capitale fédérale de la Suisse ?', c: ['Zurich', 'Genève', 'Berne', 'Lausanne'], a: 2 },
  { d: 2, q: 'Dans quel océan se trouve Madagascar ?', c: ['Atlantique', 'Indien', 'Pacifique', 'Austral'], a: 1 },
  { d: 2, q: 'Quel fleuve traverse Vienne, Budapest et Belgrade ?', c: ['Le Rhin', 'L\'Elbe', 'La Vistule', 'Le Danube'], a: 3 },
  { d: 2, q: 'Quel est le point culminant des Pyrénées ?', c: ['L\'Aneto', 'Le Vignemale', 'Le Mont Perdu', 'Le pic du Midi'], a: 0 },
  { d: 2, q: 'Quelle est la plus grande île du monde ?', c: ['Bornéo', 'Madagascar', 'Le Groenland', 'La Nouvelle-Guinée'], a: 2 },
  { d: 2, q: 'Quelle est la capitale de la Nouvelle-Zélande ?', c: ['Auckland', 'Wellington', 'Christchurch', 'Dunedin'], a: 1 },
  { d: 3, q: 'Quel archipel français se trouve au large de Terre-Neuve ?', c: ['Les Kerguelen', 'Wallis-et-Futuna', 'Les Marquises', 'Saint-Pierre-et-Miquelon'], a: 3 },
  { d: 3, q: 'Quel est le point culminant de la Corse ?', c: ['Le Monte Rotondo', 'Le Monte d\'Oro', 'La Paglia Orba', 'Le Monte Cinto'], a: 3 },
  { d: 3, q: 'Quelle est la capitale de la Birmanie (Myanmar) ?', c: ['Naypyidaw', 'Rangoun', 'Mandalay', 'Bagan'], a: 0 },
  { d: 3, q: 'Quel est le lac le plus profond du monde ?', c: ['Le lac Tanganyika', 'Le lac Supérieur', 'Le lac Baïkal', 'La mer Caspienne'], a: 2 },
  { d: 3, q: 'Quel fleuve sépare le Texas du Mexique ?', c: ['Le Colorado', 'Le Rio Grande', 'Le Mississippi', 'Le Missouri'], a: 1 },
  { d: 3, q: 'Quelle est la capitale officielle de la Tanzanie ?', c: ['Dar es Salaam', 'Arusha', 'Zanzibar', 'Dodoma'], a: 3 },
  { d: 3, q: 'Quel est le plus long fleuve d\'Europe ?', c: ['La Volga', 'Le Danube', 'Le Dniepr', 'Le Rhin'], a: 0 },
  { d: 3, q: 'Dans quel pays se trouve la ville de Tombouctou ?', c: ['Niger', 'Mauritanie', 'Mali', 'Burkina Faso'], a: 2 },
  { d: 3, q: 'Quel est le point culminant du massif des Vosges ?', c: ['Le Hohneck', 'Le Grand Ballon', 'Le Ballon d\'Alsace', 'Le Donon'], a: 1 },
  { d: 3, q: 'Quel pays est traversé à la fois par l\'équateur et par le tropique du Capricorne ?', c: ['Pérou', 'Indonésie', 'Colombie', 'Brésil'], a: 3 },
  { d: 3, q: 'Quel est le plus haut sommet d\'Amérique du Sud ?', c: ['L\'Aconcagua', 'Le Huascarán', 'Le Chimborazo', 'L\'Ojos del Salado'], a: 0 },
  { d: 3, q: 'Quel est le département le plus étendu de France métropolitaine ?', c: ['Les Landes', 'Le Var', 'La Gironde', 'La Dordogne'], a: 2 },
];
