export default [
  { d: 1, q: 'Qui est l\'autrice de la saga Harry Potter ?', c: ['Stephenie Meyer', 'Philip Pullman', 'Suzanne Collins', 'J.K. Rowling'], a: 3 },
  { d: 1, q: 'Combien de romans compte la saga Harry Potter ?', c: ['5', '6', '8', '7'], a: 3 },
  { d: 1, q: 'Dans quelle maison de Poudlard Harry est-il réparti ?', c: ['Serpentard', 'Serdaigle', 'Poufsouffle', 'Gryffondor'], a: 3 },
  { d: 1, q: 'Quel acteur incarne Harry Potter dans les films ?', c: ['Daniel Radcliffe', 'Rupert Grint', 'Tom Felton', 'Matthew Lewis'], a: 0 },
  { d: 1, q: 'Quelle actrice incarne Hermione Granger ?', c: ['Bonnie Wright', 'Emma Watson', 'Evanna Lynch', 'Katie Leung'], a: 1 },
  { d: 1, q: 'Quel est le nom de la chouette de Harry ?', c: ['Errol', 'Coquecigrue', 'Hedwige', 'Fumseck'], a: 2 },
  { d: 1, q: 'Quel sort permet de désarmer un adversaire ?', c: ['Expelliarmus', 'Stupéfix', 'Accio', 'Lumos'], a: 0 },
  { d: 1, q: 'Quel est le nom de la meilleure amie de Harry ?', c: ['Ginny Weasley', 'Luna Lovegood', 'Cho Chang', 'Hermione Granger'], a: 3 },
  { d: 1, q: 'Sur quelle voie de la gare de King\'s Cross part le Poudlard Express ?', c: ['Voie 7 ¾', 'Voie 8 ½', 'Voie 9 ¾', 'Voie 10 ½'], a: 2 },
  { d: 1, q: 'Quel est le nom du demi-géant garde-chasse de Poudlard ?', c: ['Rusard', 'Hagrid', 'Rogue', 'Slughorn'], a: 1 },
  { d: 1, q: 'Quel sport se joue sur des balais volants à Poudlard ?', c: ['Le Quidditch', 'La Bavboule', 'Le Quodpot', 'Les Échecs version sorcier'], a: 0 },
  { d: 1, q: 'Quel est le nom du seigneur des ténèbres qui a tué les parents de Harry ?', c: ['Grindelwald', 'Lucius Malefoy', 'Voldemort', 'Salazar Serpentard'], a: 2 },
  { d: 1, q: 'Quelle forme prend le Patronus de Harry ?', c: ['Un loup', 'Un phénix', 'Une loutre', 'Un cerf'], a: 3 },
  { d: 1, q: 'Quel est le titre du premier tome de la saga ?', c: ['Harry Potter à l\'école des sorciers', 'Harry Potter et la Chambre des secrets', 'Harry Potter et le Prisonnier d\'Azkaban', 'Harry Potter et la Coupe de feu'], a: 0 },
  { d: 3, q: 'En quelle année le premier tome a-t-il été publié au Royaume-Uni ?', c: ['1995', '1997', '1999', '2001'], a: 1 },
  { d: 3, q: 'En quelle année le premier film Harry Potter est-il sorti au cinéma ?', c: ['1999', '2000', '2001', '2002'], a: 2 },
  { d: 2, q: 'Quel acteur incarne Severus Rogue ?', c: ['Gary Oldman', 'Ralph Fiennes', 'Jason Isaacs', 'Alan Rickman'], a: 3 },
  { d: 2, q: 'Quel acteur incarne Voldemort à partir du quatrième film ?', c: ['Ralph Fiennes', 'Gary Oldman', 'David Thewlis', 'Timothy Spall'], a: 0 },
  { d: 3, q: 'Quel réalisateur a mis en scène les deux premiers films ?', c: ['David Yates', 'Chris Columbus', 'Alfonso Cuarón', 'Mike Newell'], a: 1 },
  { d: 2, q: 'Quel est le nom du balai que Harry reçoit en première année ?', c: ['Éclair de feu', 'Comète 260', 'Nimbus 2000', 'Brossdur 5'], a: 2 },
  { d: 3, q: 'Combien de points rapporte la capture du Vif d\'or ?', c: ['50', '100', '150', '200'], a: 2 },
  { d: 2, q: 'Quel est le nom du rat de Ron ?', c: ['Croûtard', 'Pattenrond', 'Touffu', 'Crockdur'], a: 0 },
  { d: 2, q: 'Quel est le nom de la maison familiale des Weasley ?', c: ['Le Manoir', 'Le Terrier', 'La Chaumière', 'Square Grimmaurd'], a: 1 },
  { d: 2, q: 'Quel sort fait apparaître un Patronus ?', c: ['Expecto Patronum', 'Protego', 'Riddikulus', 'Finite Incantatem'], a: 0 },
  { d: 2, q: 'Quel professeur dirige la maison Gryffondor ?', c: ['Flitwick', 'Chourave', 'Rogue', 'McGonagall'], a: 3 },
  { d: 2, q: 'Quel est le vrai nom de Voldemort dans la version française ?', c: ['Tom Elvis Jedusor', 'Tom Marvolo Riddle', 'Gellert Grindelwald', 'Barty Croupton'], a: 0 },
  { d: 2, q: 'Quel personnage meurt à la fin de Harry Potter et la Coupe de feu ?', c: ['Sirius Black', 'Cedric Diggory', 'Albus Dumbledore', 'Fred Weasley'], a: 1 },
  { d: 2, q: 'Quelle créature à trois têtes garde la trappe dans le premier tome ?', c: ['Aragog', 'Norbert', 'Buck', 'Touffu'], a: 3 },
  { d: 2, q: 'Quelle potion permet de prendre l\'apparence d\'une autre personne ?', c: ['Veritaserum', 'Felix Felicis', 'Polynectar', 'Amortentia'], a: 2 },
  { d: 2, q: 'Quel est le nom de l\'elfe de maison libéré par Harry grâce à une chaussette ?', c: ['Kreattur', 'Dobby', 'Winky', 'Hokey'], a: 1 },
  { d: 2, q: 'Quel est le nom de la prison des sorciers gardée par les Détraqueurs ?', c: ['Nurmengard', 'Azkaban', 'Durmstrang', 'Gringotts'], a: 1 },
  { d: 2, q: 'Quelle actrice incarne Bellatrix Lestrange ?', c: ['Maggie Smith', 'Imelda Staunton', 'Emma Thompson', 'Helena Bonham Carter'], a: 3 },
  { d: 3, q: 'Quel réalisateur a mis en scène Harry Potter et le Prisonnier d\'Azkaban ?', c: ['Chris Columbus', 'Mike Newell', 'Alfonso Cuarón', 'David Yates'], a: 2 },
  { d: 3, q: 'En quelle année le septième tome, Les Reliques de la Mort, a-t-il été publié ?', c: ['2005', '2006', '2007', '2008'], a: 2 },
  { d: 3, q: 'Quel acteur a incarné Dumbledore dans les deux premiers films ?', c: ['Michael Gambon', 'Richard Harris', 'Ian McKellen', 'Jim Broadbent'], a: 1 },
  { d: 3, q: 'Quelle forme prend le Patronus de Severus Rogue ?', c: ['Un cerf', 'Un serpent', 'Une biche', 'Un corbeau'], a: 2 },
  { d: 3, q: 'Quel est le nom de la rue où habitent les Dursley ?', c: ['Privet Drive', 'Grimmauld Place', 'Spinner\'s End', 'Diagon Alley'], a: 0 },
  { d: 3, q: 'Quel Maraudeur porte le surnom de Queudver ?', c: ['Sirius Black', 'Remus Lupin', 'James Potter', 'Peter Pettigrow'], a: 3 },
  { d: 3, q: 'De quel bois est faite la baguette de Harry ?', c: ['Houx', 'If', 'Vigne', 'Saule'], a: 0 },
  { d: 3, q: 'Quel personnage a réellement ouvert la Chambre des secrets dans le deuxième tome ?', c: ['Drago Malefoy', 'Ginny Weasley', 'Gilderoy Lockhart', 'Hagrid'], a: 1 },
];
