export default [
  { d: 1, q: 'En quelle année a eu lieu la prise de la Bastille ?', c: ['1789', '1792', '1799', '1815'], a: 0 },
  { d: 1, q: 'En quelle année Christophe Colomb a-t-il atteint l\'Amérique ?', c: ['1453', '1492', '1515', '1520'], a: 1 },
  { d: 1, q: 'Qui a été le premier empereur romain ?', c: ['Jules César', 'Néron', 'Auguste', 'Trajan'], a: 2 },
  { d: 1, q: 'En quelle année a eu lieu le débarquement allié en Normandie ?', c: ['1940', '1942', '1943', '1944'], a: 3 },
  { d: 1, q: 'En quelle année la Première Guerre mondiale a-t-elle commencé ?', c: ['1914', '1912', '1916', '1918'], a: 0 },
  { d: 1, q: 'Quel mur est tombé le 9 novembre 1989 ?', c: ['Le mur d\'Hadrien', 'Le mur de Berlin', 'La Grande Muraille', 'Le mur de l\'Atlantique'], a: 1 },
  { d: 1, q: 'Qui a été le premier homme à marcher sur la Lune, en 1969 ?', c: ['Buzz Aldrin', 'Youri Gagarine', 'Neil Armstrong', 'John Glenn'], a: 2 },
  { d: 1, q: 'Quel général a lancé l\'appel du 18 juin 1940 depuis Londres ?', c: ['Philippe Leclerc', 'Jean de Lattre', 'Philippe Pétain', 'Charles de Gaulle'], a: 3 },
  { d: 1, q: 'En quelle année a été signé l\'armistice qui a mis fin à la Première Guerre mondiale ?', c: ['1918', '1917', '1919', '1920'], a: 0 },
  { d: 1, q: 'Quelle bataille Napoléon a-t-il perdue en 1815 ?', c: ['Austerlitz', 'Waterloo', 'Iéna', 'Trafalgar'], a: 1 },
  { d: 1, q: 'Qui a été le premier président des États-Unis ?', c: ['Thomas Jefferson', 'Abraham Lincoln', 'George Washington', 'John Adams'], a: 2 },
  { d: 1, q: 'Dans quel château a été signé le traité de paix avec l\'Allemagne en 1919 ?', c: ['Fontainebleau', 'Chambord', 'Vincennes', 'Versailles'], a: 3 },
  { d: 1, q: 'Quelle civilisation a construit les pyramides de Gizeh ?', c: ['Les Égyptiens', 'Les Mayas', 'Les Sumériens', 'Les Perses'], a: 0 },
  { d: 1, q: 'Quel dirigeant a été à la tête de l\'Union soviétique de 1924 à 1953 ?', c: ['Lénine', 'Staline', 'Khrouchtchev', 'Trotski'], a: 1 },
  { d: 2, q: 'En quelle année Constantinople a-t-elle été prise par les Ottomans ?', c: ['1204', '1389', '1453', '1492'], a: 2 },
  { d: 2, q: 'Qui a été assassiné à Sarajevo le 28 juin 1914 ?', c: ['Guillaume II', 'Nicolas II', 'François-Joseph', 'François-Ferdinand'], a: 3 },
  { d: 2, q: 'Quels traités ont mis fin à la guerre de Trente Ans en 1648 ?', c: ['Les traités de Westphalie', 'Le traité d\'Utrecht', 'Le traité de Vienne', 'Le traité de Nimègue'], a: 0 },
  { d: 2, q: 'En quelle année l\'esclavage a-t-il été définitivement aboli dans les colonies françaises ?', c: ['1794', '1848', '1830', '1870'], a: 1 },
  { d: 2, q: 'Quelle bataille de 1415 a été une grande victoire anglaise pendant la guerre de Cent Ans ?', c: ['Crécy', 'Poitiers', 'Azincourt', 'Castillon'], a: 2 },
  { d: 2, q: 'En quelle année la Ve République a-t-elle été fondée ?', c: ['1946', '1954', '1962', '1958'], a: 3 },
  { d: 2, q: 'Qui a conduit l\'Inde à l\'indépendance en 1947 par la non-violence ?', c: ['Gandhi', 'Nehru', 'Jinnah', 'Bose'], a: 0 },
  { d: 2, q: 'Quel empereur romain a autorisé le christianisme par l\'édit de Milan en 313 ?', c: ['Dioclétien', 'Constantin', 'Théodose', 'Julien'], a: 1 },
  { d: 2, q: 'En quelle année a eu lieu la bataille d\'Hastings ?', c: ['1000', '1042', '1066', '1099'], a: 2 },
  { d: 2, q: 'Quelle ville romaine a été ensevelie par l\'éruption du Vésuve en 79 ?', c: ['Ostie', 'Capoue', 'Naples', 'Pompéi'], a: 3 },
  { d: 2, q: 'Quel navigateur portugais a atteint l\'Inde par la mer en 1498 ?', c: ['Vasco de Gama', 'Magellan', 'Bartolomeu Dias', 'Cabral'], a: 0 },
  { d: 2, q: 'Quel roi d\'Angleterre a rompu avec Rome et fondé l\'Église anglicane au XVIe siècle ?', c: ['Édouard VI', 'Henri VIII', 'Henri VII', 'Richard III'], a: 1 },
  { d: 2, q: 'Quel général carthaginois a traversé les Alpes avec des éléphants pour attaquer Rome ?', c: ['Hamilcar', 'Hasdrubal', 'Hannibal', 'Scipion'], a: 2 },
  { d: 2, q: 'Quelle bataille marque la défaite de Vercingétorix face à César en 52 av. J.-C. ?', c: ['Gergovie', 'Bibracte', 'Avaricum', 'Alésia'], a: 3 },
  { d: 3, q: 'En quelle année l\'édit de Nantes a-t-il été signé ?', c: ['1598', '1572', '1610', '1685'], a: 0 },
  { d: 3, q: 'Quel révolutionnaire a été guillotiné le 10 thermidor an II (28 juillet 1794) ?', c: ['Danton', 'Robespierre', 'Marat', 'Desmoulins'], a: 1 },
  { d: 3, q: 'En quelle année Rome a-t-elle été fondée selon la tradition ?', c: ['509 av. J.-C.', '1000 av. J.-C.', '753 av. J.-C.', '625 av. J.-C.'], a: 2 },
  { d: 3, q: 'Quel traité de 843 a partagé l\'empire de Charlemagne entre ses petits-fils ?', c: ['Traité de Meerssen', 'Traité d\'Aix-la-Chapelle', 'Traité de Coulaines', 'Traité de Verdun'], a: 3 },
  { d: 3, q: 'Quelle cité grecque a vaincu les Perses à Marathon en 490 av. J.-C. ?', c: ['Athènes', 'Sparte', 'Thèbes', 'Corinthe'], a: 0 },
  { d: 3, q: 'En quelle année l\'Empire romain d\'Occident a-t-il disparu ?', c: ['410', '476', '395', '527'], a: 1 },
  { d: 3, q: 'Quel homme d\'État prussien a réalisé l\'unification allemande proclamée en 1871 ?', c: ['Metternich', 'Moltke', 'Bismarck', 'Hindenburg'], a: 2 },
  { d: 3, q: 'En quelle année a eu lieu le sacre de Charlemagne à Rome ?', c: ['768', '774', '814', '800'], a: 3 },
  { d: 3, q: 'En quelle année l\'Algérie a-t-elle obtenu son indépendance ?', c: ['1962', '1954', '1958', '1965'], a: 0 },
  { d: 3, q: 'Quel traité de 1494 a partagé les terres du Nouveau Monde entre l\'Espagne et le Portugal ?', c: ['Traité de Madrid', 'Traité de Tordesillas', 'Traité de Lisbonne', 'Traité de Saragosse'], a: 1 },
  { d: 3, q: 'Qui a été le premier chancelier de la République fédérale d\'Allemagne en 1949 ?', c: ['Willy Brandt', 'Ludwig Erhard', 'Konrad Adenauer', 'Helmut Schmidt'], a: 2 },
  { d: 3, q: 'Quel coup d\'État a porté Bonaparte au pouvoir le 9 novembre 1799 ?', c: ['Le 9 Thermidor', 'Le 13 Vendémiaire', 'Le 18 Fructidor', 'Le 18 Brumaire'], a: 3 },
];
