export default [
  { d: 1, q: 'Dans quelle ville se déroule le ZEvent, marathon caritatif de streamers ?', c: ['Montpellier', 'Lyon', 'Bordeaux', 'Toulouse'], a: 0 },
  { d: 1, q: 'Avec qui ZeratoR co-organise-t-il le ZEvent ?', c: ['Dach', 'Domingo', 'Gotaga', 'Sardoche'], a: 0 },
  { d: 1, q: 'Quel est le vrai nom du youtubeur Squeezie ?', c: ['Lucas Hauchard', 'Norman Thavaud', 'Cyprien Iov', 'Maxime Chabroud'], a: 0 },
  { d: 1, q: 'Sur quel circuit s\'est disputé le GP Explorer organisé par Squeezie ?', c: ['Magny-Cours', 'Paul Ricard', 'Nogaro', 'Circuit Bugatti du Mans'], a: 3 },
  { d: 1, q: 'Quels sont les vrais prénoms du duo Mcfly et Carlito ?', c: ['David et Raphaël', 'Lucas et Cyprien', 'Thomas et Julien', 'Kevin et Maxime'], a: 0 },
  { d: 1, q: 'Quel sommet Inoxtag a-t-il gravi en 2024 ?', c: ['L\'Everest', 'Le Mont-Blanc', 'Le Kilimandjaro', 'L\'Aconcagua'], a: 0 },
  { d: 1, q: 'Quel est le vrai nom du youtubeur Cyprien ?', c: ['Cyprien Dubois', 'Cyprien Lopez', 'Cyprien Travers', 'Cyprien Iov'], a: 3 },
  { d: 1, q: 'Comment s\'appelle la chaîne YouTube historique de Norman ?', c: ['Norman en vrai', 'Le Monde de Norman', 'Norman Show', 'Norman fait des vidéos'], a: 3 },
  { d: 1, q: 'Quelle radio a lancé la plateforme de blogs Skyblog ?', c: ['NRJ', 'Fun Radio', 'Radio Nova', 'Skyrock'], a: 3 },
  { d: 1, q: 'En quelle année Dailymotion a-t-il été fondé ?', c: ['2001', '2003', '2007', '2005'], a: 3 },
  { d: 1, q: 'En quelle année le service Minitel a-t-il été définitivement arrêté ?', c: ['2005', '2008', '2010', '2012'], a: 3 },
  { d: 1, q: 'Quel journal Le Gorafi parodie-t-il dans son nom ?', c: ['Libération', 'Le Monde', 'Le Figaro', 'Le Parisien'], a: 2 },
  { d: 1, q: 'De quel domaine traite principalement le youtubeur Tibo InShape ?', c: ['La cuisine', 'Le cinéma', 'Les jeux vidéo', 'La musculation'], a: 3 },
  { d: 1, q: 'Sur quelle plateforme se déroule le ZEvent ?', c: ['Twitch', 'TikTok', 'Dailymotion', 'Facebook'], a: 0 },
  { d: 2, q: 'À quel institut les dons du ZEvent 2019 ont-ils été reversés ?', c: ['Institut Curie', 'Institut Gustave-Roussy', 'Institut du Cerveau', 'Institut Pasteur'], a: 3 },
  { d: 2, q: 'Quelle association a bénéficié des dons du ZEvent 2020 ?', c: ['Restos du Cœur', 'Médecins du Monde', 'Amnesty International', 'Emmaüs'], a: 2 },
  { d: 2, q: 'Quel montant environ le ZEvent 2021 a-t-il récolté ?', c: ['3 millions d\'euros', '5 millions d\'euros', '10 millions d\'euros', '20 millions d\'euros'], a: 2 },
  { d: 2, q: 'En quelle année le premier événement portant le nom ZEvent a-t-il eu lieu ?', c: ['2015', '2016', '2017', '2018'], a: 2 },
  { d: 2, q: 'Quelle association a reçu les dons du ZEvent 2021 ?', c: ['Action contre la faim', 'WWF', 'Unicef', 'Secours populaire'], a: 0 },
  { d: 2, q: 'En quelle année a eu lieu le premier GP Explorer ?', c: ['2020', '2021', '2022', '2023'], a: 2 },
  { d: 2, q: 'Avec quel président Mcfly et Carlito ont-ils tourné un concours d\'anecdotes à l\'Élysée en 2021 ?', c: ['Nicolas Sarkozy', 'François Hollande', 'Jacques Chirac', 'Emmanuel Macron'], a: 3 },
  { d: 2, q: 'Comment s\'appelle le documentaire d\'Inoxtag sur son ascension de l\'Everest ?', c: ['Sommet', 'Horizon', 'Ikigai', 'Kaizen'], a: 3 },
  { d: 2, q: 'Quel streamer a cofondé l\'équipe d\'esport Karmine Corp ?', c: ['Gotaga', 'ZeratoR', 'Kameto', 'Squeezie'], a: 2 },
  { d: 2, q: 'Quel est le vrai nom du Joueur du Grenier ?', c: ['Sébastien Rassiat', 'Frédéric Molas', 'Benjamin Brillaud', 'Bruce Benamran'], a: 1 },
  { d: 2, q: 'Quelle émission YouTube a rendu célèbre Antoine Daniel ?', c: ['What the Cut !?', 'Le Fossoyeur de Films', 'Bref', 'Le Dézapping'], a: 0 },
  { d: 2, q: 'Comment s\'appelle l\'émission de Domingo diffusée sur Twitch ?', c: ['Backseat', 'Popcorn', 'Le Stream', 'La Matinée'], a: 1 },
  { d: 2, q: 'Quel animateur de « Questions pour un champion » fait des revues de presse sur Twitch ?', c: ['Julien Lepers', 'Samuel Étienne', 'Nagui', 'Cyril Féraud'], a: 1 },
  { d: 2, q: 'En quelle année Skyblog a-t-il fermé ses portes ?', c: ['2019', '2021', '2023', '2024'], a: 2 },
  { d: 3, q: 'Quel forum de jeuxvideo.com est resté célèbre pour ses débordements ?', c: ['Le forum 15-18 ans', 'Le forum 18-25 ans', 'Le forum 25-35 ans', 'Le forum Blabla moins de 15 ans'], a: 1 },
  { d: 3, q: 'Qui a fondé BlaBlaCar, à l\'origine nommé Covoiturage.fr ?', c: ['Xavier Niel', 'Frédéric Mazzella', 'Jacques-Antoine Granjon', 'Marc Simoncini'], a: 1 },
  { d: 3, q: 'Quel est le vrai nom de la youtubeuse Léna Situations ?', c: ['Léna Mahfouf', 'Marie Lopez', 'Natoo Odiot', 'Léna Travers'], a: 0 },
  { d: 3, q: 'Quel est le vrai nom du streamer ZeratoR ?', c: ['Alexandre Dachary', 'Adrien Nougaret', 'Pierre Alexis Bizot', 'Corentin Houssein'], a: 1 },
  { d: 3, q: 'Quelle association a reçu les dons du ZEvent 2018 ?', c: ['Croix-Rouge française', 'Médecins sans frontières', 'Save the Children', 'Institut Pasteur'], a: 1 },
  { d: 3, q: 'Quelle association a reçu les dons du ZEvent 2017 ?', c: ['Croix-Rouge française', 'Amnesty International', 'Action contre la faim', 'Emmaüs'], a: 0 },
  { d: 3, q: 'Sous quel nom s\'est tenu en 2016 l\'événement précurseur du ZEvent ?', c: ['Projet Marvel', 'Projet Avengers', 'Projet Héros', 'Projet Justice'], a: 1 },
  { d: 3, q: 'Quel pilote a remporté le premier GP Explorer en 2022 ?', c: ['Depielo', 'Sylvain Lévy', 'Squeezie', 'Michou'], a: 1 },
  { d: 3, q: 'Quelle ligue européenne de League of Legends Karmine Corp a-t-elle rejointe en 2024 ?', c: ['LFL', 'LCK', 'LEC', 'LCS'], a: 2 },
  { d: 3, q: 'Quelle émission politique Jean Massiet anime-t-il sur Twitch ?', c: ['Popcorn', 'Backseat', 'Le Stream', 'Sans Filtre'], a: 1 },
  { d: 3, q: 'Quel groupe a pris le contrôle de Dailymotion en 2015 ?', c: ['Orange', 'Canal+', 'Vivendi', 'TF1'], a: 2 },
  { d: 3, q: 'En quelle année le groupe Webedia a-t-il racheté jeuxvideo.com ?', c: ['2010', '2012', '2014', '2016'], a: 2 },
];
