export default [
  { d: 1, q: 'Qui a créé le personnage de Mario ?', c: ['Hideo Kojima', 'Yuji Naka', 'Satoru Iwata', 'Shigeru Miyamoto'], a: 3 },
  { d: 1, q: 'Quelle entreprise a créé Sonic le hérisson ?', c: ['Nintendo', 'Capcom', 'Konami', 'Sega'], a: 3 },
  { d: 1, q: 'Comment s\'appelle le héros de la série The Legend of Zelda ?', c: ['Link', 'Zelda', 'Ganon', 'Epona'], a: 0 },
  { d: 1, q: 'Quel personnage incarne-t-on dans la série Tomb Raider ?', c: ['Samus Aran', 'Jill Valentine', 'Chun-Li', 'Lara Croft'], a: 3 },
  { d: 1, q: 'Quel est le nom du frère de Mario ?', c: ['Wario', 'Yoshi', 'Toad', 'Luigi'], a: 3 },
  { d: 1, q: 'Quelle entreprise fabrique la PlayStation ?', c: ['Sony', 'Microsoft', 'Nintendo', 'Sega'], a: 0 },
  { d: 1, q: 'En quelle année la Nintendo Switch est-elle sortie ?', c: ['2015', '2016', '2018', '2017'], a: 3 },
  { d: 1, q: 'Quel studio développe Fortnite ?', c: ['Activision', 'Ubisoft', 'Electronic Arts', 'Epic Games'], a: 3 },
  { d: 1, q: 'Quel est le numéro de Pikachu dans le Pokédex national ?', c: ['1', '151', '100', '25'], a: 3 },
  { d: 1, q: 'Qui est le créateur original de Minecraft ?', c: ['Markus Persson', 'Gabe Newell', 'Tim Sweeney', 'Will Wright'], a: 0 },
  { d: 1, q: 'Quel studio développe la série Grand Theft Auto ?', c: ['Bethesda', 'BioWare', 'Naughty Dog', 'Rockstar Games'], a: 3 },
  { d: 1, q: 'Quel éditeur français est à l\'origine d\'Assassin\'s Creed ?', c: ['Quantic Dream', 'Arkane', 'Ubisoft', 'Dontnod'], a: 2 },
  { d: 1, q: 'Comment s\'appelle le héros de la série God of War ?', c: ['Kratos', 'Dante', 'Marcus Fenix', 'Master Chief'], a: 0 },
  { d: 1, q: 'Quel est le nom de la princesse que Mario sauve régulièrement ?', c: ['Daisy', 'Zelda', 'Peach', 'Rosalina'], a: 2 },
  { d: 3, q: 'En quelle année Pac-Man est-il sorti en salle d\'arcade ?', c: ['1978', '1980', '1982', '1985'], a: 1 },
  { d: 3, q: 'Qui a créé Tetris en 1984 ?', c: ['Alexeï Pajitnov', 'Nolan Bushnell', 'Toru Iwatani', 'Tomohiro Nishikado'], a: 0 },
  { d: 2, q: 'Quel studio japonais a créé la série Final Fantasy ?', c: ['Enix', 'Capcom', 'Square', 'Sega'], a: 2 },
  { d: 3, q: 'En quelle année la première PlayStation est-elle sortie au Japon ?', c: ['1992', '1994', '1996', '1998'], a: 1 },
  { d: 2, q: 'Quel studio a développé The Witcher 3 ?', c: ['Larian Studios', 'Bethesda', 'CD Projekt Red', 'Obsidian'], a: 2 },
  { d: 2, q: 'Comment s\'appelle l\'héroïne de la série Metroid ?', c: ['Samus Aran', 'Bayonetta', 'Aloy', 'Ellie'], a: 0 },
  { d: 3, q: 'Quelle société a racheté Mojang, le studio de Minecraft, en 2014 ?', c: ['Sony', 'Tencent', 'Microsoft', 'Amazon'], a: 2 },
  { d: 2, q: 'Quel studio a développé Doom en 1993 ?', c: ['id Software', 'Valve', 'Epic Games', '3D Realms'], a: 0 },
  { d: 2, q: 'Comment s\'appelle le héros de Half-Life ?', c: ['Adrian Shephard', 'Gordon Freeman', 'Isaac Clarke', 'Duke Nukem'], a: 1 },
  { d: 2, q: 'Quel studio a développé la série Uncharted ?', c: ['Insomniac Games', 'Santa Monica Studio', 'Sucker Punch', 'Naughty Dog'], a: 3 },
  { d: 2, q: 'Quelle console Sega est sortie après la Saturn ?', c: ['Mega Drive', 'Dreamcast', 'Game Gear', 'Master System'], a: 1 },
  { d: 2, q: 'Qui est le créateur de la série Metal Gear ?', c: ['Hideo Kojima', 'Hidetaka Miyazaki', 'Shinji Mikami', 'Yoshinori Ono'], a: 0 },
  { d: 2, q: 'Comment s\'appelle l\'intelligence artificielle antagoniste de Portal ?', c: ['SHODAN', 'HAL', 'GLaDOS', 'Cortana'], a: 2 },
  { d: 2, q: 'En quelle année le premier Super Mario Bros. est-il sorti ?', c: ['1983', '1985', '1987', '1989'], a: 1 },
  { d: 2, q: 'Quel studio a développé Elden Ring ?', c: ['Capcom', 'Platinum Games', 'Atlus', 'FromSoftware'], a: 3 },
  { d: 2, q: 'Quelle société finlandaise a créé Angry Birds ?', c: ['Supercell', 'Remedy', 'Rovio', 'Housemarque'], a: 2 },
  { d: 2, q: 'Comment s\'appelle le royaume de Zelda ?', c: ['Hyrule', 'Termina', 'Lorule', 'Koholint'], a: 0 },
  { d: 2, q: 'Quel studio a créé Overwatch en 2016 ?', c: ['Valve', 'Riot Games', 'Blizzard', 'Bungie'], a: 2 },
  { d: 3, q: 'Quelle société a commercialisé Pong en 1972 ?', c: ['Magnavox', 'Atari', 'Nintendo', 'Taito'], a: 1 },
  { d: 3, q: 'En quelle année Space Invaders est-il sorti ?', c: ['1976', '1978', '1980', '1982'], a: 1 },
  { d: 3, q: 'Quel studio britannique a créé Tomb Raider en 1996 ?', c: ['Rare', 'Core Design', 'Rockstar North', 'Crystal Dynamics'], a: 1 },
  { d: 3, q: 'Qui a créé Stardew Valley, sorti en 2016 ?', c: ['Toby Fox', 'Jonathan Blow', 'Eric Barone', 'Edmund McMillen'], a: 2 },
  { d: 3, q: 'Quel studio a développé Halo : Combat Evolved en 2001 ?', c: ['343 Industries', 'Bungie', 'Epic Games', 'Gearbox'], a: 1 },
  { d: 3, q: 'Quel créateur français est à l\'origine de Rayman ?', c: ['Michel Ancel', 'David Cage', 'Éric Chahi', 'Frédérick Raynal'], a: 0 },
  { d: 3, q: 'En quelle année la plateforme Steam a-t-elle été lancée ?', c: ['2001', '2003', '2005', '2007'], a: 1 },
  { d: 3, q: 'Comment s\'appelle la cité sous-marine de BioShock ?', c: ['Columbia', 'Atlantis', 'Rapture', 'Eden'], a: 2 },
];
