export default [
  { d: 1, q: 'Quel légume est à la base de la choucroute ?', c: ['Navet', 'Poireau', 'Chou', 'Céleri'], a: 2 },
  { d: 1, q: 'Quel petit légume vert et rond pousse dans une cosse ?', c: ['Haricot vert', 'Petit pois', 'Fève', 'Lentille'], a: 1 },
  { d: 1, q: 'Quel légume sec est l\'ingrédient principal du houmous ?', c: ['Lentille', 'Haricot', 'Fève', 'Pois chiche'], a: 3 },
  { d: 1, q: 'Quel légume est un emblème du pays de Galles ?', c: ['Navet', 'Poireau', 'Oignon', 'Chou'], a: 1 },
  { d: 1, q: 'Quel légume accompagne les courgettes, poivrons et tomates dans la ratatouille ?', c: ['Aubergine', 'Concombre', 'Fenouil', 'Artichaut'], a: 0 },
  { d: 1, q: 'Quel légume fait pleurer lorsqu\'on l\'épluche ?', c: ['Ail', 'Poireau', 'Oignon', 'Céleri'], a: 2 },
  { d: 1, q: 'Quel ingrédient est à la base du guacamole ?', c: ['Courgette', 'Petit pois', 'Concombre', 'Avocat'], a: 3 },
  { d: 1, q: 'Quelle grosse cucurbitacée orange sert de lanterne à Halloween ?', c: ['Citrouille', 'Courgette', 'Melon', 'Pâtisson'], a: 0 },
  { d: 1, q: 'De quel légume sont faites les frites traditionnelles ?', c: ['Patate douce', 'Manioc', 'Pomme de terre', 'Igname'], a: 2 },
  { d: 1, q: 'Quel légume vert donne sa force au personnage de Popeye ?', c: ['Brocoli', 'Épinard', 'Chou kale', 'Cresson'], a: 1 },
  { d: 1, q: 'De quelle céréale le pop-corn est-il fait ?', c: ['Blé', 'Riz', 'Orge', 'Maïs'], a: 3 },
  { d: 1, q: 'Le cornichon est la jeune version de quel légume ?', c: ['Courgette', 'Concombre', 'Courge', 'Haricot'], a: 1 },
  { d: 1, q: 'Lequel de ces légumes est une racine ?', c: ['Poireau', 'Chou', 'Carotte', 'Épinard'], a: 2 },
  { d: 1, q: 'Que produit-on à partir de la betterave sucrière ?', c: ['Du sucre', 'De l\'huile', 'De la farine', 'Du vinaigre'], a: 0 },
  { d: 2, q: 'Dans quelle région du monde la pomme de terre a-t-elle été domestiquée ?', c: ['Les Andes', 'L\'Irlande', 'L\'Espagne', 'La Chine'], a: 0 },
  { d: 2, q: 'Quel légume est l\'ingrédient principal du bortsch ?', c: ['Chou', 'Carotte', 'Betterave', 'Pomme de terre'], a: 2 },
  { d: 2, q: 'Quel légume est obtenu par forçage à l\'obscurité des racines de chicorée ?', c: ['Asperge', 'Endive', 'Chou-fleur', 'Céleri'], a: 1 },
  { d: 2, q: 'À quelle famille botanique appartient la tomate ?', c: ['Cucurbitacées', 'Brassicacées', 'Apiacées', 'Solanacées'], a: 3 },
  { d: 2, q: 'À quelle famille botanique appartient la carotte ?', c: ['Apiacées', 'Solanacées', 'Fabacées', 'Astéracées'], a: 0 },
  { d: 2, q: 'Quel légume était autrefois appelé « pomme d\'amour » ?', c: ['Aubergine', 'Poivron', 'Tomate', 'Courgette'], a: 2 },
  { d: 2, q: 'Qui a popularisé la pomme de terre en France au XVIIIe siècle ?', c: ['Vauban', 'Parmentier', 'Colbert', 'Lavoisier'], a: 1 },
  { d: 2, q: 'Dans quelle région française l\'oignon de Roscoff est-il cultivé ?', c: ['Normandie', 'Alsace', 'Provence', 'Bretagne'], a: 3 },
  { d: 2, q: 'De quel continent la tomate est-elle originaire ?', c: ['Asie', 'Afrique', 'Amérique', 'Europe'], a: 2 },
  { d: 2, q: 'Quel pigment donne sa couleur orange à la carotte ?', c: ['Chlorophylle', 'Lycopène', 'Anthocyane', 'Carotène'], a: 3 },
  { d: 2, q: 'À quel genre botanique appartiennent l\'ail, l\'oignon et le poireau ?', c: ['Allium', 'Brassica', 'Daucus', 'Beta'], a: 0 },
  { d: 2, q: 'Quelle échelle mesure le piquant des piments ?', c: ['Richter', 'Scoville', 'Beaufort', 'Mohs'], a: 1 },
  { d: 2, q: 'Quelle partie de la plante est la pomme de terre ?', c: ['Une racine', 'Un bulbe', 'Un tubercule', 'Un rhizome'], a: 2 },
  { d: 2, q: 'Quelle ville est réputée pour ses lentilles vertes AOP ?', c: ['Vichy', 'Aurillac', 'Rodez', 'Le Puy-en-Velay'], a: 3 },
  { d: 3, q: 'Chou-fleur, brocoli et chou de Bruxelles sont des variétés de quelle espèce botanique ?', c: ['Brassica rapa', 'Brassica napus', 'Brassica oleracea', 'Brassica nigra'], a: 2 },
  { d: 3, q: 'Quelle partie de l\'artichaut appelle-t-on le « fond » ?', c: ['La tige', 'Le réceptacle', 'Les bractées', 'La racine'], a: 1 },
  { d: 3, q: 'Quel légume bénéficie de l\'AOP « Coco de Paimpol » ?', c: ['Haricot', 'Pois', 'Oignon', 'Chou'], a: 0 },
  { d: 3, q: 'Quel pigment donne sa couleur rouge à la tomate ?', c: ['Carotène', 'Anthocyane', 'Chlorophylle', 'Lycopène'], a: 3 },
  { d: 3, q: 'À quel genre botanique appartiennent le poivron et le piment ?', c: ['Solanum', 'Capsicum', 'Allium', 'Cucumis'], a: 1 },
  { d: 3, q: 'Quelle molécule est responsable du piquant du piment ?', c: ['Allicine', 'Solanine', 'Capsaïcine', 'Pipérine'], a: 2 },
  { d: 3, q: 'Quelle substance toxique se concentre dans les parties vertes de la pomme de terre ?', c: ['Solanine', 'Ricine', 'Nicotine', 'Strychnine'], a: 0 },
  { d: 3, q: 'De quelle région du monde l\'aubergine est-elle originaire ?', c: ['Le Mexique', 'L\'Égypte', 'L\'Italie', 'L\'Inde'], a: 3 },
  { d: 3, q: 'De quel continent le manioc est-il originaire ?', c: ['Afrique', 'Amérique du Sud', 'Asie', 'Océanie'], a: 1 },
  { d: 3, q: 'À quelle famille botanique appartient la patate douce ?', c: ['Solanacées', 'Convolvulacées', 'Cucurbitacées', 'Fabacées'], a: 1 },
  { d: 3, q: 'Le topinambour est le tubercule d\'une plante de quel genre ?', c: ['Solanum', 'Brassica', 'Helianthus', 'Daucus'], a: 2 },
  { d: 3, q: 'Quel légume servait de lanterne en Irlande avant l\'adoption de la citrouille ?', c: ['Betterave', 'Courge', 'Chou', 'Navet'], a: 3 },
];
