export default [
  { d: 1, q: 'Qui a écrit « Les Misérables » ?', c: ['Émile Zola', 'Victor Hugo', 'Honoré de Balzac', 'Alexandre Dumas'], a: 1 },
  { d: 1, q: 'Qui est l\'auteur du « Petit Prince » ?', c: ['Antoine de Saint-Exupéry', 'Jules Verne', 'Marcel Pagnol', 'Jean Giono'], a: 0 },
  { d: 1, q: 'Qui a écrit « Roméo et Juliette » ?', c: ['Charles Dickens', 'Oscar Wilde', 'William Shakespeare', 'Jane Austen'], a: 2 },
  { d: 1, q: 'Qui est l\'auteur des « Trois Mousquetaires » ?', c: ['Victor Hugo', 'Gustave Flaubert', 'Stendhal', 'Alexandre Dumas'], a: 3 },
  { d: 1, q: 'Quel personnage de Jules Verne fait le tour du monde en quatre-vingts jours ?', c: ['Michel Strogoff', 'Phileas Fogg', 'Cyrus Smith', 'Otto Lidenbrock'], a: 1 },
  { d: 1, q: 'Qui a écrit la série « Harry Potter » ?', c: ['J. K. Rowling', 'Stephen King', 'Roald Dahl', 'Philip Pullman'], a: 0 },
  { d: 1, q: 'Qui est l\'auteur de « L\'Étranger » ?', c: ['Jean-Paul Sartre', 'André Gide', 'Albert Camus', 'Louis Aragon'], a: 2 },
  { d: 1, q: 'Qui a écrit « Madame Bovary » ?', c: ['Guy de Maupassant', 'Honoré de Balzac', 'Émile Zola', 'Gustave Flaubert'], a: 3 },
  { d: 1, q: 'Qui est l\'auteur du « Seigneur des anneaux » ?', c: ['C. S. Lewis', 'J. R. R. Tolkien', 'George R. R. Martin', 'Terry Pratchett'], a: 1 },
  { d: 1, q: 'Quel écrivain du XVIIe siècle est célèbre pour ses Fables ?', c: ['Jean de La Fontaine', 'Charles Perrault', 'Nicolas Boileau', 'Jean Racine'], a: 0 },
  { d: 1, q: 'Qui a écrit la comédie « L\'Avare » ?', c: ['Pierre Corneille', 'Jean Racine', 'Molière', 'Beaumarchais'], a: 2 },
  { d: 1, q: 'Qui a écrit « Vingt mille lieues sous les mers » ?', c: ['Alexandre Dumas', 'Victor Hugo', 'Hector Malot', 'Jules Verne'], a: 3 },
  { d: 1, q: 'Comment s\'appelle le capitaine du Nautilus ?', c: ['Capitaine Haddock', 'Capitaine Nemo', 'Capitaine Achab', 'Capitaine Grant'], a: 1 },
  { d: 1, q: 'Qui est l\'auteur de « Germinal » ?', c: ['Émile Zola', 'Victor Hugo', 'Gustave Flaubert', 'Alphonse Daudet'], a: 0 },
  { d: 2, q: 'En quelle année le prix Goncourt a-t-il été décerné pour la première fois ?', c: ['1896', '1910', '1903', '1921'], a: 2 },
  { d: 2, q: 'Qui a écrit « À la recherche du temps perdu » ?', c: ['André Gide', 'Paul Valéry', 'Louis-Ferdinand Céline', 'Marcel Proust'], a: 3 },
  { d: 2, q: 'Qui est l\'auteur de « Cent ans de solitude » ?', c: ['Jorge Luis Borges', 'Gabriel García Márquez', 'Mario Vargas Llosa', 'Pablo Neruda'], a: 1 },
  { d: 2, q: 'Quel mouvement littéraire André Breton a-t-il fondé avec son manifeste de 1924 ?', c: ['Le surréalisme', 'Le dadaïsme', 'Le symbolisme', 'Le naturalisme'], a: 0 },
  { d: 2, q: 'Qui a écrit le roman « 1984 » ?', c: ['Aldous Huxley', 'Ray Bradbury', 'George Orwell', 'H. G. Wells'], a: 2 },
  { d: 2, q: 'En quelle année le roman « 1984 » a-t-il été publié ?', c: ['1932', '1945', '1955', '1949'], a: 3 },
  { d: 2, q: 'Qui est l\'auteur de « Don Quichotte » ?', c: ['Lope de Vega', 'Miguel de Cervantès', 'Federico García Lorca', 'Calderón'], a: 1 },
  { d: 2, q: 'Qui a écrit le conte philosophique « Candide » ?', c: ['Voltaire', 'Rousseau', 'Diderot', 'Montesquieu'], a: 0 },
  { d: 2, q: 'Qui est l\'auteur de « Crime et Châtiment » ?', c: ['Léon Tolstoï', 'Anton Tchekhov', 'Fiodor Dostoïevski', 'Nicolas Gogol'], a: 2 },
  { d: 2, q: 'Qui a écrit « Le Rouge et le Noir » ?', c: ['Honoré de Balzac', 'Gustave Flaubert', 'Prosper Mérimée', 'Stendhal'], a: 3 },
  { d: 2, q: 'Qui est l\'auteur du recueil « Les Fleurs du mal » ?', c: ['Paul Verlaine', 'Charles Baudelaire', 'Arthur Rimbaud', 'Stéphane Mallarmé'], a: 1 },
  { d: 2, q: 'Qui a reçu le premier prix Nobel de littérature en 1901 ?', c: ['Sully Prudhomme', 'Rudyard Kipling', 'Anatole France', 'Frédéric Mistral'], a: 0 },
  { d: 2, q: 'Qui a écrit le roman « Bel-Ami » ?', c: ['Émile Zola', 'Alphonse Daudet', 'Guy de Maupassant', 'Jules Barbey d\'Aurevilly'], a: 2 },
  { d: 2, q: 'Quel est le nom du héros du « Comte de Monte-Cristo » ?', c: ['Julien Sorel', 'Georges Duroy', 'Eugène de Rastignac', 'Edmond Dantès'], a: 3 },
  { d: 3, q: 'Quel écrivain a refusé le prix Nobel de littérature en 1964 ?', c: ['Albert Camus', 'Jean-Paul Sartre', 'Samuel Beckett', 'André Malraux'], a: 1 },
  { d: 3, q: 'En quelle année « Madame Bovary » a-t-il été publié en volume ?', c: ['1857', '1842', '1869', '1877'], a: 0 },
  { d: 3, q: 'Qui est l\'auteur de « La Princesse de Clèves » ?', c: ['Madame de Sévigné', 'Madame de Staël', 'Madame de La Fayette', 'George Sand'], a: 2 },
  { d: 3, q: 'Qui a écrit « Voyage au bout de la nuit » ?', c: ['Jean Genet', 'Georges Bernanos', 'Raymond Queneau', 'Louis-Ferdinand Céline'], a: 3 },
  { d: 3, q: 'Qui est l\'auteur du roman « Le Nom de la rose » ?', c: ['Italo Calvino', 'Umberto Eco', 'Primo Levi', 'Alberto Moravia'], a: 1 },
  { d: 3, q: 'Qui a écrit « Les Liaisons dangereuses » ?', c: ['Choderlos de Laclos', 'L\'abbé Prévost', 'Marivaux', 'Le marquis de Sade'], a: 0 },
  { d: 3, q: 'Quel écrivain a créé le personnage du commissaire Maigret ?', c: ['Maurice Leblanc', 'Gaston Leroux', 'Georges Simenon', 'Frédéric Dard'], a: 2 },
  { d: 3, q: 'Sous quel nom de plume Aurore Dupin est-elle connue ?', c: ['Colette', 'Rachilde', 'Daniel Stern', 'George Sand'], a: 3 },
  { d: 3, q: 'Qui est l\'auteur de « Belle du Seigneur » ?', c: ['Romain Gary', 'Albert Cohen', 'Joseph Kessel', 'Marguerite Duras'], a: 1 },
  { d: 3, q: 'Qui a écrit le roman « Ulysse », publié en 1922 ?', c: ['James Joyce', 'Virginia Woolf', 'Samuel Beckett', 'D. H. Lawrence'], a: 0 },
  { d: 3, q: 'Quel écrivain a refusé le prix Goncourt en 1951 pour « Le Rivage des Syrtes » ?', c: ['Henri Michaux', 'René Char', 'Julien Gracq', 'Michel Butor'], a: 2 },
  { d: 3, q: 'Quelle femme de lettres a été la première élue à l\'Académie française, en 1980 ?', c: ['Simone de Beauvoir', 'Nathalie Sarraute', 'Françoise Sagan', 'Marguerite Yourcenar'], a: 3 },
];
