export default [
  { d: 1, q: 'Quel studio développe League of Legends ?', c: ['Blizzard', 'Riot Games', 'Valve', 'Epic Games'], a: 1 },
  { d: 1, q: 'En quelle année League of Legends est-il sorti ?', c: ['2007', '2011', '2013', '2009'], a: 3 },
  { d: 1, q: 'Combien de joueurs compose une équipe sur la Faille de l\'invocateur ?', c: ['3', '4', '6', '5'], a: 3 },
  { d: 1, q: 'Quelle structure faut-il détruire pour remporter une partie ?', c: ['Le Nexus', 'L\'Inhibiteur', 'La Tour', 'Le Baron'], a: 0 },
  { d: 1, q: 'Quel est le nom de la carte principale de League of Legends ?', c: ['La Forêt torturée', 'La Faille de l\'invocateur', 'L\'Abîme hurlant', 'Le Bassin cristallin'], a: 1 },
  { d: 1, q: 'Quel est le vrai nom du joueur Faker ?', c: ['Lee Sang-hyeok', 'Kim Hyuk-kyu', 'Jian Zi-Hao', 'Bae Jun-sik'], a: 0 },
  { d: 1, q: 'Dans quelle équipe Faker a-t-il joué toute sa carrière ?', c: ['Gen.G', 'DRX', 'Samsung White', 'T1'], a: 3 },
  { d: 1, q: 'Quel champion est un renard à neuf queues ?', c: ['Ahri', 'Lulu', 'Nami', 'Kindred'], a: 0 },
  { d: 1, q: 'Quel champion est le frère de Yasuo ?', c: ['Zed', 'Yone', 'Shen', 'Kayn'], a: 1 },
  { d: 1, q: 'En quelle année la série Arcane est-elle sortie sur Netflix ?', c: ['2019', '2020', '2022', '2021'], a: 3 },
  { d: 1, q: 'Quelles deux sœurs sont au cœur de la série Arcane ?', c: ['Lux et Ashe', 'Ahri et Akali', 'Caitlyn et Jayce', 'Vi et Jinx'], a: 3 },
  { d: 1, q: 'Quel gros monstre neutre se trouve dans la fosse en haut de la rivière ?', c: ['Le Dragon ancestral', 'Le Héraut de la Faille', 'Le Golem bleu', 'Le Baron Nashor'], a: 3 },
  { d: 1, q: 'Quel champion yordle pose des champignons piégés ?', c: ['Ziggs', 'Tristana', 'Corki', 'Teemo'], a: 3 },
  { d: 1, q: 'Quel est le niveau maximal d\'un champion dans une partie ?', c: ['16', '18', '20', '30'], a: 1 },
  { d: 2, q: 'Quelle équipe a remporté les premiers Worlds en 2011 ?', c: ['Counter Logic Gaming', 'Fnatic', 'Team SoloMid', 'against All authority'], a: 1 },
  { d: 2, q: 'Quelle équipe a remporté les Worlds 2012 ?', c: ['Azubu Frost', 'Moscow Five', 'CLG.EU', 'Taipei Assassins'], a: 3 },
  { d: 2, q: 'Quelle équipe a remporté les Worlds 2014 ?', c: ['Samsung White', 'Samsung Blue', 'Royal Club', 'OMG'], a: 0 },
  { d: 2, q: 'Quelle équipe a remporté les Worlds 2018 ?', c: ['Fnatic', 'Royal Never Give Up', 'Invictus Gaming', 'G2 Esports'], a: 2 },
  { d: 2, q: 'Quelle équipe a remporté les Worlds 2019 face à G2 Esports ?', c: ['FunPlus Phoenix', 'SK Telecom T1', 'Invictus Gaming', 'DAMWON Gaming'], a: 0 },
  { d: 2, q: 'Quelle équipe a remporté les Worlds 2020 ?', c: ['Top Esports', 'DAMWON Gaming', 'Suning', 'JD Gaming'], a: 1 },
  { d: 2, q: 'Quelle équipe a remporté les Worlds 2022 ?', c: ['Gen.G', 'JD Gaming', 'T1', 'DRX'], a: 3 },
  { d: 2, q: 'Quelle équipe a remporté les Worlds 2021 ?', c: ['EDward Gaming', 'DWG KIA', 'Royal Never Give Up', 'Gen.G'], a: 0 },
  { d: 2, q: 'Quelle ligue régionale réunit les équipes européennes ?', c: ['LCS', 'LPL', 'LEC', 'LCK'], a: 2 },
  { d: 2, q: 'Quel pays abrite la ligue LCK ?', c: ['Chine', 'Corée du Sud', 'Japon', 'Taïwan'], a: 1 },
  { d: 2, q: 'Comment s\'appelle le sort d\'invocateur qui permet de se téléporter sur une courte distance ?', c: ['Embrasement', 'Fantôme', 'Soins', 'Saut éclair'], a: 3 },
  { d: 2, q: 'De quelle nation de Runeterra est originaire Garen ?', c: ['Noxus', 'Ionia', 'Demacia', 'Shurima'], a: 2 },
  { d: 2, q: 'De quelle cité est originaire Jinx ?', c: ['Zaun', 'Piltover', 'Bilgewater', 'Bandle City'], a: 0 },
  { d: 2, q: 'Quel champion est le frère de Lux ?', c: ['Jarvan IV', 'Garen', 'Xin Zhao', 'Sylas'], a: 1 },
  { d: 3, q: 'Quel studio d\'animation français a réalisé la série Arcane ?', c: ['Fortiche', 'Ankama', 'Illumination Mac Guff', 'Cube'], a: 0 },
  { d: 3, q: 'Quel jeu de combat automatique dérivé de League of Legends est sorti en 2019 ?', c: ['Legends of Runeterra', 'Wild Rift', 'Teamfight Tactics', 'Ruined King'], a: 2 },
  { d: 3, q: 'Quelle équipe française a intégré le LEC en 2024 ?', c: ['Team Vitality', 'Solary', 'Karmine Corp', 'LDLC OL'], a: 2 },
  { d: 3, q: 'Quel champion originaire du Néant est un insecte capable de muter ?', c: ['Kha\'Zix', 'Rengar', 'Elise', 'Skarner'], a: 0 },
  { d: 3, q: 'Dans quelle ville s\'est jouée la finale des Worlds 2019 ?', c: ['Berlin', 'Madrid', 'Paris', 'Londres'], a: 2 },
  { d: 3, q: 'Dans quelle enceinte s\'est jouée la finale des Worlds 2017 ?', c: ['Stade national de Pékin', 'Mercedes-Benz Arena', 'Staples Center', 'Stade de Munhak'], a: 0 },
  { d: 3, q: 'Quel joueur de Fnatic est célèbre pour son backdoor avec Kassadin contre SK Gaming en 2013 ?', c: ['Rekkles', 'YellOwStaR', 'xPeke', 'Cyanide'], a: 2 },
  { d: 3, q: 'Quels sont les deux fondateurs de Riot Games ?', c: ['Gabe Newell et Mike Harrington', 'Brandon Beck et Marc Merrill', 'Tim Sweeney et Mark Rein', 'Allen Adham et Mike Morhaime'], a: 1 },
  { d: 3, q: 'Quelle équipe a remporté les Worlds 2017 en battant SK Telecom T1 en finale ?', c: ['Royal Never Give Up', 'Longzhu Gaming', 'Samsung Galaxy', 'Team WE'], a: 2 },
  { d: 3, q: 'Dans quelle ville s\'est jouée la finale des Worlds 2015 ?', c: ['Londres', 'Séoul', 'Berlin', 'Paris'], a: 2 },
  { d: 3, q: 'Quel joueur a mené DRX au titre mondial en 2022 sur le poste d\'ADC ?', c: ['Ruler', 'Deft', 'Gumayusi', 'Uzi'], a: 1 },
  { d: 3, q: 'Quelle championne complète le groupe K/DA avec Ahri, Akali et Evelynn ?', c: ['Seraphine', 'Miss Fortune', 'Kai\'Sa', 'Lux'], a: 2 },
];
