export default [
  { d: 1, q: 'Quelle dynastie régnait sur la Chine en 1444 ?', c: ['Les Song', 'Les Ming', 'Les Qing', 'Les Yuan'], a: 1 },
  { d: 1, q: 'Quelle ville était la capitale de l\'Empire byzantin en 1444 ?', c: ['Athènes', 'Nicée', 'Thessalonique', 'Constantinople'], a: 3 },
  { d: 1, q: 'Quel conflit opposait la France et l\'Angleterre en 1444 ?', c: ['La guerre de Cent Ans', 'La guerre de Trente Ans', 'La guerre des Deux-Roses', 'La guerre de Sept Ans'], a: 0 },
  { d: 1, q: 'Quel peuple dominait la vallée de Mexico en 1444 ?', c: ['Les Mayas', 'Les Olmèques', 'Les Aztèques', 'Les Toltèques'], a: 2 },
  { d: 1, q: 'Quelle civilisation dominait la région de Cuzco, dans les Andes, en 1444 ?', c: ['Les Mayas', 'Les Incas', 'Les Aztèques', 'Les Mapuches'], a: 1 },
  { d: 1, q: 'Quelle invention Gutenberg mettait-il au point à Mayence dans les années 1440 ?', c: ['La boussole', 'La poudre à canon', 'La lunette astronomique', 'L\'imprimerie à caractères mobiles'], a: 3 },
  { d: 1, q: 'Quel continent les Européens n\'avaient-ils pas encore atteint en 1444 ?', c: ['L\'Amérique', 'L\'Afrique', 'L\'Asie', 'L\'Europe'], a: 0 },
  { d: 1, q: 'Quel royaume européen explorait la côte ouest de l\'Afrique dans les années 1440 ?', c: ['L\'Angleterre', 'La France', 'Le Portugal', 'La Suède'], a: 2 },
  { d: 1, q: 'Quel pays était gouverné par Henri VI en 1444 ?', c: ['La France', 'L\'Angleterre', 'La Castille', 'L\'Écosse'], a: 1 },
  { d: 1, q: 'En quelle année Constantinople est-elle tombée aux mains des Ottomans ?', c: ['1444', '1492', '1517', '1453'], a: 3 },
  { d: 1, q: 'Quelle était la capitale des Aztèques en 1444 ?', c: ['Tenochtitlan', 'Teotihuacan', 'Chichén Itzá', 'Cuzco'], a: 0 },
  { d: 1, q: 'Quel empire contrôlait l\'Anatolie et une grande partie des Balkans en 1444 ?', c: ['L\'Empire mongol', 'L\'Empire perse', 'L\'Empire ottoman', 'L\'Empire russe'], a: 2 },
  { d: 1, q: 'Quelle épidémie avait ravagé l\'Europe un siècle plus tôt, entre 1347 et 1352 ?', c: ['Le choléra', 'La peste noire', 'La variole', 'La grippe espagnole'], a: 1 },
  { d: 1, q: 'Quelle jeune femme, brûlée à Rouen en 1431, avait conduit Charles VII au sacre de Reims ?', c: ['Aliénor d\'Aquitaine', 'Christine de Pizan', 'Agnès Sorel', 'Jeanne d\'Arc'], a: 3 },
  { d: 2, q: 'Qui était roi de France en 1444 ?', c: ['Charles VII', 'Louis XI', 'Charles VI', 'Philippe VI'], a: 0 },
  { d: 2, q: 'Quelle bataille de novembre 1444 vit les Ottomans écraser une croisade en Bulgarie ?', c: ['Nicopolis', 'Kosovo', 'Varna', 'Mohács'], a: 2 },
  { d: 2, q: 'Quel sultan ottoman régnait en 1444 et remporta la bataille de Varna ?', c: ['Bayezid Ier', 'Mourad II', 'Mehmed II', 'Sélim Ier'], a: 1 },
  { d: 2, q: 'Quelle trêve fut signée en 1444 entre la France et l\'Angleterre ?', c: ['La paix d\'Arras', 'Le traité de Troyes', 'Le traité de Brétigny', 'La trêve de Tours'], a: 3 },
  { d: 2, q: 'Quel prince portugais encourageait les expéditions maritimes le long de l\'Afrique dans les années 1440 ?', c: ['Henri le Navigateur', 'Vasco de Gama', 'Manuel Ier', 'Bartolomeu Dias'], a: 0 },
  { d: 2, q: 'Quel État musulman gouvernait Delhi en 1444 ?', c: ['L\'Empire moghol', 'L\'Empire maurya', 'Le sultanat de Delhi', 'L\'Empire marathe'], a: 2 },
  { d: 2, q: 'Quelle dynastie régnait sur la Corée en 1444 ?', c: ['Goryeo', 'Joseon', 'Silla', 'Goguryeo'], a: 1 },
  { d: 2, q: 'Qui était duc de Bourgogne en 1444 ?', c: ['Jean sans Peur', 'Philippe le Hardi', 'Charles le Téméraire', 'Philippe le Bon'], a: 3 },
  { d: 2, q: 'Quelle union réunissait le Danemark, la Suède et la Norvège sous un même souverain en 1444 ?', c: ['L\'union de Kalmar', 'La Hanse', 'L\'union de Lublin', 'L\'union d\'Utrecht'], a: 0 },
  { d: 2, q: 'Quel royaume musulman subsistait encore dans le sud de la péninsule Ibérique en 1444 ?', c: ['Le califat de Cordoue', 'Le royaume de Séville', 'Le royaume de Grenade', 'Le royaume de Tolède'], a: 2 },
  { d: 2, q: 'Quelle maison régnait sur l\'Angleterre en 1444 ?', c: ['Les Tudor', 'Les Lancastre', 'Les York', 'Les Stuart'], a: 1 },
  { d: 2, q: 'Quelle était la capitale de la Chine des Ming en 1444 ?', c: ['Nankin', 'Xi\'an', 'Hangzhou', 'Pékin'], a: 3 },
  { d: 2, q: 'Quel amiral chinois avait mené sept expéditions maritimes jusque dans l\'océan Indien, la dernière s\'achevant en 1433 ?', c: ['Zheng He', 'Zhu Di', 'Xu Fu', 'Wang Yangming'], a: 0 },
  { d: 2, q: 'Quelle famille dominait Florence en 1444 ?', c: ['Les Sforza', 'Les Borgia', 'Les Médicis', 'Les Gonzague'], a: 2 },
  { d: 3, q: 'Quel roi de Corée fit promulguer l\'alphabet hangeul en 1446 ?', c: ['Taejo', 'Sejong', 'Sejo', 'Gojong'], a: 1 },
  { d: 3, q: 'Quel Habsbourg était roi des Romains en 1444, avant d\'être couronné empereur en 1452 ?', c: ['Maximilien Ier', 'Sigismond', 'Albert II', 'Frédéric III'], a: 3 },
  { d: 3, q: 'Quel cap africain, longtemps réputé infranchissable, le Portugais Gil Eanes avait-il doublé en 1434 ?', c: ['Le cap Bojador', 'Le cap de Bonne-Espérance', 'Le cap Vert', 'Le cap Blanc'], a: 0 },
  { d: 3, q: 'Qui régnait sur l\'Empire timouride en 1444 ?', c: ['Tamerlan', 'Babur', 'Shah Rukh', 'Ulugh Beg'], a: 2 },
  { d: 3, q: 'Quel grand-prince régnait sur Moscou en 1444 ?', c: ['Ivan III', 'Vassili II', 'Dimitri Donskoï', 'Ivan IV'], a: 1 },
  { d: 3, q: 'Quel roi de Pologne et de Hongrie fut tué à la bataille de Varna en 1444 ?', c: ['Casimir IV', 'Sigismond de Luxembourg', 'Matthias Corvin', 'Ladislas III'], a: 3 },
  { d: 3, q: 'Quel chef militaire hongrois commandait les troupes chrétiennes à Varna en 1444 ?', c: ['Jean Hunyadi', 'Matthias Corvin', 'Étienne Báthory', 'Vlad Dracul'], a: 0 },
  { d: 3, q: 'Quel empereur byzantin régnait en 1444 ?', c: ['Constantin XI', 'Manuel II', 'Jean VIII Paléologue', 'Andronic IV'], a: 2 },
  { d: 3, q: 'Quelle ville était la capitale de l\'Empire ottoman en 1444 ?', c: ['Bursa', 'Edirne', 'Constantinople', 'Konya'], a: 1 },
  { d: 3, q: 'Quel shogunat gouvernait le Japon en 1444 ?', c: ['Kamakura', 'Tokugawa', 'Minamoto', 'Ashikaga'], a: 3 },
  { d: 3, q: 'Quel roi d\'Aragon avait conquis le royaume de Naples en 1442 ?', c: ['Alphonse V le Magnanime', 'Ferdinand le Catholique', 'Jacques Ier', 'Pierre IV'], a: 0 },
  { d: 3, q: 'Quel empire hindou dominait le sud de l\'Inde en 1444 ?', c: ['L\'Empire chola', 'Le sultanat de Bahmani', 'L\'Empire de Vijayanagara', 'L\'Empire gupta'], a: 2 },
];
