export default [
  { d: 1, q: 'Quel groupe de Seattle a sorti l\'album « Nevermind » en 1991 ?', c: ['Nirvana', 'Pearl Jam', 'Soundgarden', 'Alice in Chains'], a: 0 },
  { d: 1, q: 'Quelle chanteuse canadienne interprète « My Heart Will Go On », chanson du film « Titanic » (1997) ?', c: ['Shania Twain', 'Céline Dion', 'Alanis Morissette', 'Sarah McLachlan'], a: 1 },
  { d: 1, q: 'Quel groupe de rap marseillais a sorti l\'album « L\'École du micro d\'argent » en 1997 ?', c: ['NTM', 'Assassin', 'IAM', 'Fonky Family'], a: 2 },
  { d: 1, q: 'Quel groupe britannique a sorti « Wonderwall » en 1995 ?', c: ['Blur', 'Pulp', 'Radiohead', 'Oasis'], a: 3 },
  { d: 1, q: 'Quel groupe féminin britannique a sorti « Wannabe » en 1996 ?', c: ['Spice Girls', 'All Saints', 'Sugababes', 'Girls Aloud'], a: 0 },
  { d: 1, q: 'Quel duo français a sorti l\'album « Discovery » en 2001 ?', c: ['Justice', 'Daft Punk', 'Air', 'Cassius'], a: 1 },
  { d: 1, q: 'En quelle année Michael Jackson est-il mort ?', c: ['2007', '2008', '2009', '2010'], a: 2 },
  { d: 1, q: 'Quel groupe toulousain a interprété « Tomber la chemise » ?', c: ['Louise Attaque', 'Manau', 'Tryo', 'Zebda'], a: 3 },
  { d: 1, q: 'Quelle chanteuse américaine a sorti « ...Baby One More Time » en 1998 ?', c: ['Britney Spears', 'Christina Aguilera', 'Jessica Simpson', 'Mandy Moore'], a: 0 },
  { d: 1, q: 'Quel rappeur américain a sorti l\'album « The Marshall Mathers LP » en 2000 ?', c: ['Dr. Dre', 'Eminem', '50 Cent', 'Jay-Z'], a: 1 },
  { d: 1, q: 'Quel groupe français a sorti « J\'ai demandé à la lune » en 2002 ?', c: ['Kyo', 'Louise Attaque', 'Indochine', 'Superbus'], a: 2 },
  { d: 1, q: 'Quel chanteur britannique a sorti « Angels » en 1997 ?', c: ['Gary Barlow', 'Ronan Keating', 'George Michael', 'Robbie Williams'], a: 3 },
  { d: 1, q: 'Quel groupe américain a sorti l\'album « Californication » en 1999 ?', c: ['Red Hot Chili Peppers', 'Green Day', 'Foo Fighters', 'Blink-182'], a: 0 },
  { d: 1, q: 'Quelle chanteuse a sorti « Umbrella » en 2007 ?', c: ['Beyoncé', 'Rihanna', 'Alicia Keys', 'Kelly Rowland'], a: 1 },
  { d: 2, q: 'Quel groupe de rap de Seine-Saint-Denis est formé par JoeyStarr et Kool Shen ?', c: ['IAM', 'Ministère A.M.E.R.', 'NTM', 'Lunatic'], a: 2 },
  { d: 2, q: 'Quelle comédie musicale française de 1998 a révélé Garou et Hélène Ségara ?', c: ['Roméo et Juliette', 'Les Dix Commandements', 'Starmania', 'Notre-Dame de Paris'], a: 3 },
  { d: 2, q: 'Quel groupe britannique a sorti l\'album « OK Computer » en 1997 ?', c: ['Radiohead', 'Blur', 'The Verve', 'Suede'], a: 0 },
  { d: 2, q: 'Quel chanteur français a sorti « Foule sentimentale » en 1993 ?', c: ['Laurent Voulzy', 'Alain Souchon', 'Francis Cabrel', 'Alain Bashung'], a: 1 },
  { d: 2, q: 'Quel rappeur américain a été tué par balles à Las Vegas en 1996 ?', c: ['The Notorious B.I.G.', 'Eazy-E', '2Pac', 'Big L'], a: 2 },
  { d: 2, q: 'Quelle chanteuse islandaise a sorti l\'album « Debut » en 1993 ?', c: ['Sinéad O\'Connor', 'Tori Amos', 'PJ Harvey', 'Björk'], a: 3 },
  { d: 2, q: 'Quel groupe britannique a sorti l\'album « Parklife » en 1994 ?', c: ['Blur', 'Pulp', 'Supergrass', 'Elastica'], a: 0 },
  { d: 2, q: 'Quel duo français a sorti l\'album « Moon Safari » en 1998 ?', c: ['Phoenix', 'Air', 'M83', 'Étienne de Crécy'], a: 1 },
  { d: 2, q: 'Quel est le nom de scène de Matthieu Chedid ?', c: ['Bénabar', 'Raphaël', '-M-', 'Cali'], a: 2 },
  { d: 2, q: 'Quel groupe américain a sorti l\'album « American Idiot » en 2004 ?', c: ['Blink-182', 'The Offspring', 'Sum 41', 'Green Day'], a: 3 },
  { d: 2, q: 'Quel groupe britannique a sorti « Bitter Sweet Symphony » en 1997 ?', c: ['The Verve', 'Travis', 'Coldplay', 'Embrace'], a: 0 },
  { d: 2, q: 'En quelle année est sorti l\'album « Back to Black » d\'Amy Winehouse ?', c: ['2004', '2006', '2007', '2008'], a: 1 },
  { d: 2, q: 'Quel rappeur français a sorti l\'album « Ouest Side » en 2006 ?', c: ['Rohff', 'Sinik', 'Booba', 'Kery James'], a: 2 },
  { d: 2, q: 'Quelle chanteuse américaine a sorti « Poker Face » en 2008 ?', c: ['Katy Perry', 'Kesha', 'Fergie', 'Lady Gaga'], a: 3 },
  { d: 3, q: 'Quel groupe suédois a sorti « The Sign » en 1993 ?', c: ['Ace of Base', 'Roxette', 'The Cardigans', 'Army of Lovers'], a: 0 },
  { d: 3, q: 'Quel rappeur français a sorti l\'album « Prose combat » en 1994 ?', c: ['Doc Gynéco', 'MC Solaar', 'Oxmo Puccino', 'Akhenaton'], a: 1 },
  { d: 3, q: 'Quel groupe de metal américain a sorti l\'album « Toxicity » en 2001 ?', c: ['Korn', 'Slipknot', 'System of a Down', 'Deftones'], a: 2 },
  { d: 3, q: 'Quel groupe de rap marseillais a sorti l\'album « Si Dieu veut… » en 1997 ?', c: ['Psy 4 de la Rime', 'Le 3ème Œil', 'IAM', 'Fonky Family'], a: 3 },
  { d: 3, q: 'Quel album d\'Alain Bashung est sorti en 1998 ?', c: ['Fantaisie militaire', 'Osez Joséphine', 'Bleu pétrole', 'L\'Imprudence'], a: 0 },
  { d: 3, q: 'Quel groupe de Bristol a sorti l\'album « Dummy » en 1994 ?', c: ['Massive Attack', 'Portishead', 'Tricky', 'Morcheeba'], a: 1 },
  { d: 3, q: 'Quel groupe bordelais a sorti l\'album « Tostaky » en 1992 ?', c: ['Louise Attaque', 'Les Innocents', 'Noir Désir', 'Mano Negra'], a: 2 },
  { d: 3, q: 'En quelle année est sorti « Parachutes », le premier album de Coldplay ?', c: ['1997', '1998', '1999', '2000'], a: 3 },
  { d: 3, q: 'Quel groupe français a sorti « Lady (Hear Me Tonight) » en 2000 ?', c: ['Modjo', 'Cassius', 'Stardust', 'Justice'], a: 0 },
  { d: 3, q: 'Quelle chanteuse canadienne a sorti l\'album « Jagged Little Pill » en 1995 ?', c: ['Sheryl Crow', 'Alanis Morissette', 'Fiona Apple', 'Jewel'], a: 1 },
  { d: 3, q: 'Quel duo britannique a sorti l\'album « Dig Your Own Hole » en 1997 ?', c: ['The Prodigy', 'Fatboy Slim', 'The Chemical Brothers', 'Underworld'], a: 2 },
  { d: 3, q: 'Quelle chanteuse française a sorti « Ma philosophie » en 2004 ?', c: ['Jenifer', 'Nolwenn Leroy', 'Diam\'s', 'Amel Bent'], a: 3 },
];
