export default [
  { d: 1, q: 'Quel groupe suédois a remporté l\'Eurovision en 1974 avec « Waterloo » ?', c: ['ABBA', 'Roxette', 'Ace of Base', 'Europe'], a: 0 },
  { d: 1, q: 'Quel chanteur américain a sorti l\'album « Thriller » en 1982 ?', c: ['Prince', 'Michael Jackson', 'Stevie Wonder', 'Lionel Richie'], a: 1 },
  { d: 1, q: 'Quel groupe britannique a sorti l\'album « The Dark Side of the Moon » en 1973 ?', c: ['Led Zeppelin', 'Genesis', 'Pink Floyd', 'Queen'], a: 2 },
  { d: 1, q: 'Quel chanteur français a interprété « Mistral gagnant » en 1985 ?', c: ['Michel Berger', 'Alain Souchon', 'Francis Cabrel', 'Renaud'], a: 3 },
  { d: 1, q: 'Qui était le chanteur du groupe Queen ?', c: ['Freddie Mercury', 'Brian May', 'Roger Taylor', 'John Deacon'], a: 0 },
  { d: 1, q: 'En quelle année Elvis Presley est-il mort ?', c: ['1975', '1977', '1979', '1981'], a: 1 },
  { d: 1, q: 'En quelle année John Lennon a-t-il été assassiné à New York ?', c: ['1978', '1979', '1980', '1982'], a: 2 },
  { d: 1, q: 'Quelle chanteuse a sorti « Like a Virgin » en 1984 ?', c: ['Cyndi Lauper', 'Whitney Houston', 'Tina Turner', 'Madonna'], a: 3 },
  { d: 1, q: 'Quel groupe irlandais a sorti l\'album « The Joshua Tree » en 1987 ?', c: ['U2', 'The Cranberries', 'Thin Lizzy', 'The Pogues'], a: 0 },
  { d: 1, q: 'Quel chanteur belge a interprété « Ça plane pour moi » en 1977 ?', c: ['Jacques Brel', 'Plastic Bertrand', 'Arno', 'Salvatore Adamo'], a: 1 },
  { d: 1, q: 'Quel groupe australien a sorti l\'album « Back in Black » en 1980 ?', c: ['INXS', 'Midnight Oil', 'AC/DC', 'Men at Work'], a: 2 },
  { d: 1, q: 'Quel chanteur américain a sorti l\'album « Born in the U.S.A. » en 1984 ?', c: ['Bob Dylan', 'Billy Joel', 'Tom Petty', 'Bruce Springsteen'], a: 3 },
  { d: 1, q: 'Quelle chanteuse a fait gagner la France à l\'Eurovision en 1977 avec « L\'Oiseau et l\'Enfant » ?', c: ['Marie Myriam', 'Sheila', 'Dalida', 'France Gall'], a: 0 },
  { d: 1, q: 'Quel groupe français a sorti « Marcia Baila » en 1984 ?', c: ['Indochine', 'Les Rita Mitsouko', 'Téléphone', 'Niagara'], a: 1 },
  { d: 2, q: 'En quelle année les Beatles se sont-ils officiellement séparés ?', c: ['1968', '1969', '1970', '1971'], a: 2 },
  { d: 2, q: 'Quel producteur a réalisé l\'album « Thriller » de Michael Jackson ?', c: ['Nile Rodgers', 'Phil Spector', 'George Martin', 'Quincy Jones'], a: 3 },
  { d: 2, q: 'Quel groupe français a sorti « L\'Aventurier » en 1982 ?', c: ['Indochine', 'Téléphone', 'Trust', 'Starshooter'], a: 0 },
  { d: 2, q: 'Quel chanteur britannique a sorti l\'album « Let\'s Dance » en 1983 ?', c: ['Elton John', 'David Bowie', 'Rod Stewart', 'Phil Collins'], a: 1 },
  { d: 2, q: 'Quel groupe britannique a sorti « Smoke on the Water » en 1972 ?', c: ['Black Sabbath', 'Led Zeppelin', 'Deep Purple', 'Uriah Heep'], a: 2 },
  { d: 2, q: 'Quel concert caritatif organisé par Bob Geldof s\'est tenu simultanément à Londres et Philadelphie en 1985 ?', c: ['Woodstock', 'Band Aid', 'Farm Aid', 'Live Aid'], a: 3 },
  { d: 2, q: 'Quelle chanteuse française a sorti « Il jouait du piano debout » en 1980 ?', c: ['France Gall', 'Véronique Sanson', 'Michèle Torr', 'Nicole Croisille'], a: 0 },
  { d: 2, q: 'Quel duo britannique a sorti « Wake Me Up Before You Go-Go » en 1984 ?', c: ['Duran Duran', 'Wham!', 'Culture Club', 'Spandau Ballet'], a: 1 },
  { d: 2, q: 'En quelle année Claude François est-il mort ?', c: ['1976', '1977', '1978', '1979'], a: 2 },
  { d: 2, q: 'Quel artiste américain a sorti l\'album « Purple Rain » en 1984 ?', c: ['Rick James', 'Lionel Richie', 'Stevie Wonder', 'Prince'], a: 3 },
  { d: 2, q: 'Quel groupe de Manchester, formé en 1976, avait pour chanteur Ian Curtis ?', c: ['Joy Division', 'The Smiths', 'New Order', 'The Stone Roses'], a: 0 },
  { d: 2, q: 'Quel instrument est au cœur de l\'album « Oxygène » de Jean-Michel Jarre, sorti en 1976 ?', c: ['Guitare', 'Synthétiseur', 'Piano', 'Saxophone'], a: 1 },
  { d: 2, q: 'Quel groupe britannique a sorti l\'album « London Calling » en 1979 ?', c: ['Sex Pistols', 'The Damned', 'The Clash', 'Buzzcocks'], a: 2 },
  { d: 2, q: 'Quel chanteur français a sorti « Quelque chose de Tennessee » en 1985 ?', c: ['Eddy Mitchell', 'Michel Sardou', 'Julien Clerc', 'Johnny Hallyday'], a: 3 },
  { d: 3, q: 'Quel groupe allemand a sorti l\'album « Autobahn » en 1974 ?', c: ['Kraftwerk', 'Can', 'Tangerine Dream', 'Scorpions'], a: 0 },
  { d: 3, q: 'En quelle année est sorti l\'album « Hotel California » des Eagles ?', c: ['1974', '1976', '1978', '1980'], a: 1 },
  { d: 3, q: 'Qui était la bassiste du groupe Téléphone ?', c: ['Jean-Louis Aubert', 'Louis Bertignac', 'Corine Marienneau', 'Richard Kolinka'], a: 2 },
  { d: 3, q: 'En quelle année Daniel Balavoine est-il mort dans un accident d\'hélicoptère lors du Paris-Dakar ?', c: ['1983', '1984', '1985', '1986'], a: 3 },
  { d: 3, q: 'Quel opéra rock de Michel Berger et Luc Plamondon a été créé sur scène en 1979 ?', c: ['Starmania', 'Notre-Dame de Paris', 'Hair', 'Mayflower'], a: 0 },
  { d: 3, q: 'Quel album-concept de Serge Gainsbourg est sorti en 1971 ?', c: ['L\'Homme à tête de chou', 'Histoire de Melody Nelson', 'Aux armes et cætera', 'Love on the Beat'], a: 1 },
  { d: 3, q: 'En quelle année Metallica a-t-il sorti son premier album, « Kill \'Em All » ?', c: ['1981', '1982', '1983', '1984'], a: 2 },
  { d: 3, q: 'Quel est le nom du groupe qui accompagnait Bob Marley ?', c: ['The Upsetters', 'The Maytals', 'The Skatalites', 'The Wailers'], a: 3 },
  { d: 3, q: 'Quel duo britannique est l\'auteur de « West End Girls » ?', c: ['Pet Shop Boys', 'Erasure', 'Soft Cell', 'Yazoo'], a: 0 },
  { d: 3, q: 'Quel groupe a sorti l\'album « Appetite for Destruction » en 1987 ?', c: ['Mötley Crüe', 'Guns N\' Roses', 'Bon Jovi', 'Poison'], a: 1 },
  { d: 3, q: 'Quel compositeur a signé la bande originale du film « Les Chariots de feu » en 1981 ?', c: ['Giorgio Moroder', 'Jean-Michel Jarre', 'Vangelis', 'Mike Oldfield'], a: 2 },
  { d: 3, q: 'Quel groupe de hard rock français a sorti « Antisocial » en 1980 ?', c: ['Téléphone', 'Starshooter', 'Bijou', 'Trust'], a: 3 },
];
