export default [
  { d: 1, q: 'Quelle chanteuse britannique a sorti l\'album « 21 » en 2011 ?', c: ['Adele', 'Amy Winehouse', 'Jessie J', 'Ellie Goulding'], a: 0 },
  { d: 1, q: 'Quel chanteur belge a sorti « Formidable » en 2013 ?', c: ['Roméo Elvis', 'Stromae', 'Damso', 'Loïc Nottet'], a: 1 },
  { d: 1, q: 'Quel chanteur canadien a sorti « Blinding Lights » en 2019 ?', c: ['Justin Bieber', 'Drake', 'The Weeknd', 'Shawn Mendes'], a: 2 },
  { d: 1, q: 'Quelle chanteuse belge a sorti « Tout oublier » en 2018 ?', c: ['Clara Luciani', 'Louane', 'Pomme', 'Angèle'], a: 3 },
  { d: 1, q: 'Quel chanteur sud-coréen a sorti « Gangnam Style » en 2012 ?', c: ['Psy', 'Rain', 'G-Dragon', 'Jungkook'], a: 0 },
  { d: 1, q: 'Quelle chanteuse américaine a sorti l\'album « 1989 » en 2014 ?', c: ['Katy Perry', 'Taylor Swift', 'Ariana Grande', 'Selena Gomez'], a: 1 },
  { d: 1, q: 'Quel rappeur français a sorti « Sapés comme jamais » en 2015 ?', c: ['Booba', 'Soprano', 'Maître Gims', 'Black M'], a: 2 },
  { d: 1, q: 'Quel groupe sud-coréen a sorti « Dynamite » en 2020 ?', c: ['Blackpink', 'EXO', 'Seventeen', 'BTS'], a: 3 },
  { d: 1, q: 'Quelle chanteuse américaine a sorti « Bad Guy » en 2019 ?', c: ['Billie Eilish', 'Dua Lipa', 'Olivia Rodrigo', 'Halsey'], a: 0 },
  { d: 1, q: 'Quel duo français a sorti l\'album « Random Access Memories » en 2013 ?', c: ['Justice', 'Daft Punk', 'The Blaze', 'Polo & Pan'], a: 1 },
  { d: 1, q: 'Quelle chanteuse française a sorti « Dernière danse » en 2013 ?', c: ['Zaz', 'Louane', 'Indila', 'Tal'], a: 2 },
  { d: 1, q: 'Quel chanteur britannique a sorti « Shape of You » en 2017 ?', c: ['Sam Smith', 'Harry Styles', 'Lewis Capaldi', 'Ed Sheeran'], a: 3 },
  { d: 1, q: 'Quel rappeur canadien a sorti « Hotline Bling » en 2015 ?', c: ['Drake', 'Kendrick Lamar', 'Travis Scott', 'Post Malone'], a: 0 },
  { d: 1, q: 'Quel chanteur américain interprète « Uptown Funk » avec Mark Ronson en 2014 ?', c: ['Pharrell Williams', 'Bruno Mars', 'Usher', 'Jason Derulo'], a: 1 },
  { d: 2, q: 'Quel rappeur belge a sorti l\'album « Ipséité » en 2017 ?', c: ['Roméo Elvis', 'Hamza', 'Damso', 'Caballero'], a: 2 },
  { d: 2, q: 'Quelle chanteuse française a sorti « Djadja » en 2018 ?', c: ['Wejdene', 'Shy\'m', 'Amel Bent', 'Aya Nakamura'], a: 3 },
  { d: 2, q: 'Quel rappeur américain a sorti l\'album « To Pimp a Butterfly » en 2015 ?', c: ['Kendrick Lamar', 'J. Cole', 'Kanye West', 'Childish Gambino'], a: 0 },
  { d: 2, q: 'Quel duo de rap français a sorti l\'album « Deux frères » en 2019 ?', c: ['Bigflo & Oli', 'PNL', 'Djadja & Dinaz', 'Casseurs Flowters'], a: 1 },
  { d: 2, q: 'Quel rappeur français a sorti l\'album « Feu » en 2015 ?', c: ['Orelsan', 'Vald', 'Nekfeu', 'Lomepal'], a: 2 },
  { d: 2, q: 'Quel rappeur français a sorti l\'album « La fête est finie » en 2017 ?', c: ['Bigflo', 'Vald', 'Lomepal', 'Orelsan'], a: 3 },
  { d: 2, q: 'Quelle chanteuse américaine a sorti l\'album « Lemonade » en 2016 ?', c: ['Beyoncé', 'Rihanna', 'Solange', 'SZA'], a: 0 },
  { d: 2, q: 'En quelle année Prince est-il mort ?', c: ['2014', '2016', '2017', '2018'], a: 1 },
  { d: 2, q: 'En quelle année Johnny Hallyday est-il mort ?', c: ['2015', '2016', '2017', '2018'], a: 2 },
  { d: 2, q: 'Quel DJ français a sorti « Titanium » avec Sia en 2011 ?', c: ['Bob Sinclar', 'Martin Solveig', 'DJ Snake', 'David Guetta'], a: 3 },
  { d: 2, q: 'Quel groupe de rock britannique a sorti l\'album « AM » en 2013 ?', c: ['Arctic Monkeys', 'The 1975', 'Kasabian', 'Foals'], a: 0 },
  { d: 2, q: 'Quelle chanteuse française a sorti « La Grenade » en 2018 ?', c: ['Juliette Armanet', 'Clara Luciani', 'Angèle', 'Pomme'], a: 1 },
  { d: 2, q: 'Quel chanteur portoricain interprète « Despacito » (2017) avec Daddy Yankee ?', c: ['Ricky Martin', 'Chayanne', 'Luis Fonsi', 'Bad Bunny'], a: 2 },
  { d: 2, q: 'Quelle chanteuse américaine a sorti « Flowers » en 2023 ?', c: ['Dua Lipa', 'Ariana Grande', 'Selena Gomez', 'Miley Cyrus'], a: 3 },
  { d: 3, q: 'Quel rappeur français a sorti l\'album « Agartha » en 2017 ?', c: ['Vald', 'SCH', 'Kaaris', 'Alkpote'], a: 0 },
  { d: 3, q: 'Quel groupe islandais a sorti « Little Talks » en 2011 ?', c: ['Sigur Rós', 'Of Monsters and Men', 'Kaleo', 'Múm'], a: 1 },
  { d: 3, q: 'Quelle chanteuse a représenté la France à l\'Eurovision 2021 avec « Voilà » ?', c: ['Alma', 'Amir', 'Barbara Pravi', 'Bilal Hassani'], a: 2 },
  { d: 3, q: 'Quel rappeur marseillais a sorti l\'album « Deo Favente » en 2017 ?', c: ['Jul', 'Naps', 'Soso Maness', 'SCH'], a: 3 },
  { d: 3, q: 'En quelle année Daft Punk a-t-il annoncé sa séparation ?', c: ['2021', '2022', '2023', '2024'], a: 0 },
  { d: 3, q: 'Quel rappeur américain a sorti « Old Town Road » en 2019 ?', c: ['Post Malone', 'Lil Nas X', 'Lil Baby', 'DaBaby'], a: 1 },
  { d: 3, q: 'Quelle chanteuse française a sorti l\'album « Consolation » en 2022 ?', c: ['Angèle', 'Clara Luciani', 'Pomme', 'Zaho de Sagazan'], a: 2 },
  { d: 3, q: 'Quel chanteur a remporté l\'Eurovision 2019 pour les Pays-Bas ?', c: ['Måneskin', 'Salvador Sobral', 'Netta', 'Duncan Laurence'], a: 3 },
  { d: 3, q: 'Quel groupe italien a remporté l\'Eurovision 2021 ?', c: ['Måneskin', 'Il Volo', 'The Kolors', 'Negramaro'], a: 0 },
  { d: 3, q: 'Quel rappeur français a sorti l\'album « Trône » en 2017 ?', c: ['Kaaris', 'Booba', 'Ninho', 'Damso'], a: 1 },
  { d: 3, q: 'Quelle chanteuse britannique a sorti l\'album « Future Nostalgia » en 2020 ?', c: ['Rita Ora', 'Charli XCX', 'Dua Lipa', 'Jessie Ware'], a: 2 },
  { d: 3, q: 'Quel rappeur français a sorti l\'album « Destin » en 2019 ?', c: ['Niska', 'Koba LaD', 'Gazo', 'Ninho'], a: 3 },
];
