export default [
  { d: 1, q: 'Quel studio développe la série Warcraft ?', c: ['Bethesda', 'Westwood', 'BioWare', 'Blizzard'], a: 3 },
  { d: 1, q: 'En quelle année World of Warcraft est-il sorti ?', c: ['2002', '2003', '2004', '2005'], a: 2 },
  { d: 1, q: 'Comment s\'appelle le monde dans lequel se déroule Warcraft ?', c: ['Draenor', 'Tamriel', 'Sanctuaire', 'Azeroth'], a: 3 },
  { d: 1, q: 'Quelles sont les deux grandes factions de World of Warcraft ?', c: ['L\'Empire et la Rébellion', 'La Légion et le Fléau', 'Les Titans et les Dieux très anciens', 'L\'Alliance et la Horde'], a: 3 },
  { d: 1, q: 'Quel personnage devient le Roi-liche après avoir pris Deuillegivre ?', c: ['Uther', 'Illidan', 'Arthas', 'Thrall'], a: 2 },
  { d: 1, q: 'Quelle est la capitale des orcs dans World of Warcraft ?', c: ['Orgrimmar', 'Hurlevent', 'Forgefer', 'Fossoyeuse'], a: 0 },
  { d: 1, q: 'Quelle est la capitale des humains dans World of Warcraft ?', c: ['Lordaeron', 'Gilnéas', 'Theramore', 'Hurlevent'], a: 3 },
  { d: 1, q: 'Quel orc devient chef de guerre de la Horde après avoir libéré son peuple ?', c: ['Grommash', 'Gul\'dan', 'Garrosh', 'Thrall'], a: 3 },
  { d: 1, q: 'Quel est le nom de l\'épée maudite portée par Arthas ?', c: ['Deuillegivre', 'Porte-cendres', 'Marteau-du-Destin', 'Shalamayne'], a: 0 },
  { d: 1, q: 'Quel jeu de cartes de Blizzard se déroule dans l\'univers de Warcraft ?', c: ['Gwent', 'Hearthstone', 'Artifact', 'Runeterra'], a: 1 },
  { d: 1, q: 'Quel demi-démon chasseur de démons est l\'antagoniste de l\'extension The Burning Crusade ?', c: ['Malfurion', 'Kael\'thas', 'Illidan', 'Sargeras'], a: 2 },
  { d: 1, q: 'Quelle extension ajoute le continent de Pandarie ?', c: ['Cataclysm', 'Legion', 'Warlords of Draenor', 'Mists of Pandaria'], a: 3 },
  { d: 1, q: 'Quelle race joue le rôle de guerriers à cornes et sabots au sein de la Horde ?', c: ['Les taurens', 'Les draeneï', 'Les worgens', 'Les nains'], a: 0 },
  { d: 1, q: 'En quelle année le film Warcraft est-il sorti au cinéma ?', c: ['2014', '2016', '2018', '2020'], a: 1 },
  { d: 2, q: 'Quel est le titre du premier jeu Warcraft, sorti en 1994 ?', c: ['Warcraft : Orcs & Humans', 'Warcraft : Tides of Darkness', 'Warcraft : Reign of Chaos', 'Warcraft : Beyond the Dark Portal'], a: 0 },
  { d: 2, q: 'En quelle année Warcraft III : Reign of Chaos est-il sorti ?', c: ['2000', '2001', '2002', '2003'], a: 2 },
  { d: 2, q: 'Quelle est la première extension de World of Warcraft, sortie en 2007 ?', c: ['Wrath of the Lich King', 'The Burning Crusade', 'Cataclysm', 'Legion'], a: 1 },
  { d: 2, q: 'Quelle extension de World of Warcraft est sortie en 2008 ?', c: ['Cataclysm', 'The Burning Crusade', 'Mists of Pandaria', 'Wrath of the Lich King'], a: 3 },
  { d: 2, q: 'Quelle extension de World of Warcraft est sortie en 2016 ?', c: ['Legion', 'Warlords of Draenor', 'Battle for Azeroth', 'Shadowlands'], a: 0 },
  { d: 2, q: 'Quelle extension de World of Warcraft est sortie en 2022 ?', c: ['Shadowlands', 'Battle for Azeroth', 'Dragonflight', 'The War Within'], a: 2 },
  { d: 2, q: 'Quelle classe a été ajoutée avec Wrath of the Lich King ?', c: ['Moine', 'Chevalier de la mort', 'Chasseur de démons', 'Évocateur'], a: 1 },
  { d: 2, q: 'Quelle classe a été ajoutée avec Legion ?', c: ['Moine', 'Chevalier de la mort', 'Chasseur de démons', 'Évocateur'], a: 2 },
  { d: 2, q: 'Quelle classe a été ajoutée avec Mists of Pandaria ?', c: ['Moine', 'Chevalier de la mort', 'Chasseur de démons', 'Évocateur'], a: 0 },
  { d: 2, q: 'Quel dragon noir est l\'antagoniste principal de l\'extension Cataclysm ?', c: ['Alexstrasza', 'Malygos', 'Aile de mort', 'Nozdormu'], a: 2 },
  { d: 2, q: 'Qui est la Reine banshee, cheffe des Réprouvés ?', c: ['Jaina Portvaillant', 'Sylvanas Coursevent', 'Tyrande Murmevent', 'Alleria Coursevent'], a: 1 },
  { d: 2, q: 'Quel seigneur du feu est le boss final du Cœur du Magma ?', c: ['Onyxia', 'Nefarian', 'C\'Thun', 'Ragnaros'], a: 3 },
  { d: 2, q: 'Quel est le nom du frère jumeau d\'Illidan ?', c: ['Malfurion', 'Cenarius', 'Furion', 'Maiev'], a: 0 },
  { d: 2, q: 'Quel Gardien de Tirisfal a ouvert la Porte des ténèbres aux orcs ?', c: ['Khadgar', 'Medivh', 'Antonidas', 'Aegwynn'], a: 1 },
  { d: 3, q: 'Quelle capitale abrite les nains dans World of Warcraft ?', c: ['Forgefer', 'Gnomeregan', 'Darnassus', 'Lune-d\'argent'], a: 0 },
  { d: 3, q: 'Quel fils de Grommash Hurlenfer devient chef de guerre de la Horde sous Cataclysm ?', c: ['Vol\'jin', 'Saurcroc', 'Garrosh', 'Nazgrel'], a: 2 },
  { d: 3, q: 'Quel Titan déchu dirige la Légion ardente ?', c: ['Aman\'Thul', 'Kil\'jaeden', 'Archimonde', 'Sargeras'], a: 3 },
  { d: 3, q: 'Quel est le niveau maximal de World of Warcraft à sa sortie en 2004 ?', c: ['50', '60', '70', '80'], a: 1 },
  { d: 3, q: 'Quel est le titre de l\'extension de Warcraft III sortie en 2003 ?', c: ['The Frozen Throne', 'Beyond the Dark Portal', 'Tides of Darkness', 'Reign of Chaos'], a: 0 },
  { d: 3, q: 'Quel paladin est tué par Arthas dans Warcraft III ?', c: ['Tirion Fordring', 'Bolvar Fordragon', 'Uther le Porteur de Lumière', 'Turalyon'], a: 2 },
  { d: 3, q: 'Quel Dieu très ancien est affronté à la fin du temple d\'Ahn\'Qiraj ?', c: ['Yogg-Saron', 'N\'Zoth', 'Y\'Shaarj', 'C\'Thun'], a: 3 },
  { d: 3, q: 'Quelle race a rejoint la Horde avec l\'extension The Burning Crusade ?', c: ['Les draeneï', 'Les elfes de sang', 'Les gobelins', 'Les pandarens'], a: 1 },
  { d: 3, q: 'Dans quelle zone se trouve la tour de Karazhan ?', c: ['Marche de l\'Ouest', 'Vallée de Strangleronce', 'Défilé de Deuillevent', 'Marais des Chagrins'], a: 2 },
  { d: 3, q: 'Quel chef tauren est tué en duel par Garrosh Hurlenfer ?', c: ['Baine Sabot-de-Sang', 'Cairne Sabot-de-Sang', 'Hamuul Totem-Runique', 'Magatha Totem-Sinistre'], a: 1 },
  { d: 3, q: 'Quel paladin humain devient Roi-liche après la mort d\'Arthas ?', c: ['Darion Mograine', 'Bolvar Fordragon', 'Tirion Fordring', 'Ner\'zhul'], a: 1 },
  { d: 3, q: 'Quel ancien Roi-liche orc a précédé Arthas ?', c: ['Ner\'zhul', 'Gul\'dan', 'Orgrim Marteau-du-Destin', 'Durotan'], a: 0 },
];
