// Rasterises the flags used by the question bank into small PNG data URIs -> fwf/flags.js
import { chromium } from 'playwright';
import fs from 'fs';
const codes = [...fs.readFileSync('/home/claude/fwf/questions/drapeaux.js', 'utf8').matchAll(/flag: '([A-Z]{2})'|cf: \[([^\]]*)\]/g)]
  .flatMap((m) => (m[1] ? [m[1]] : m[2].match(/[A-Z]{2}/g))).filter((v, i, a) => a.indexOf(v) === i).sort();
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const page = await browser.newPage({ viewport: { width: 96, height: 72 }, deviceScaleFactor: 1 });
const out = {};
for (const c of codes) {
  const svg = fs.readFileSync(`node_modules/flag-icons/flags/4x3/${c.toLowerCase()}.svg`, 'utf8');
  await page.setContent(`<body style="margin:0;background:#fff">${svg.replace('<svg', '<svg width="96" height="72"')}</body>`);
  const buf = await page.screenshot({ type: 'png', clip: { x: 0, y: 0, width: 96, height: 72 } });
  out[c] = 'data:image/png;base64,' + buf.toString('base64');
}
await browser.close();
const js = '// 96x72 PNG flags (from flag-icons, MIT) for the countries used in questions/drapeaux.js. Generated by tools/build-flags.mjs.\nexport const FLAGS = {\n' +
  Object.entries(out).map(([k, v]) => `  ${k}: '${v}',`).join('\n') + '\n};\n';
fs.writeFileSync('/home/claude/fwf/flags.js', js);
console.log(codes.length, 'flags,', Math.round(js.length / 1024), 'KB');
